// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit
{
    public static class GetModelexperimentsInstance
    {
        /// <summary>
        /// Datasource scheme for a STACKIT AI Model Experiments instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_modelexperiments_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   region      = "eu01"
        ///   instance_id = "example-instance-id"
        /// }
        /// ```
        /// </summary>
        public static Task<GetModelexperimentsInstanceResult> InvokeAsync(GetModelexperimentsInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetModelexperimentsInstanceResult>("stackit:index/getModelexperimentsInstance:getModelexperimentsInstance", args ?? new GetModelexperimentsInstanceArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource scheme for a STACKIT AI Model Experiments instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_modelexperiments_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   region      = "eu01"
        ///   instance_id = "example-instance-id"
        /// }
        /// ```
        /// </summary>
        public static Output<GetModelexperimentsInstanceResult> Invoke(GetModelexperimentsInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetModelexperimentsInstanceResult>("stackit:index/getModelexperimentsInstance:getModelexperimentsInstance", args ?? new GetModelexperimentsInstanceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource scheme for a STACKIT AI Model Experiments instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_modelexperiments_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   region      = "eu01"
        ///   instance_id = "example-instance-id"
        /// }
        /// ```
        /// </summary>
        public static Output<GetModelexperimentsInstanceResult> Invoke(GetModelexperimentsInstanceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetModelexperimentsInstanceResult>("stackit:index/getModelexperimentsInstance:getModelexperimentsInstance", args ?? new GetModelexperimentsInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetModelexperimentsInstanceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The AI Model Experiments instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        /// <summary>
        /// STACKIT Project ID to which the resource is associated.
        /// </summary>
        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        /// <summary>
        /// The STACKIT region name the resource is located in. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        public GetModelexperimentsInstanceArgs()
        {
        }
        public static new GetModelexperimentsInstanceArgs Empty => new GetModelexperimentsInstanceArgs();
    }

    public sealed class GetModelexperimentsInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The AI Model Experiments instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        /// <summary>
        /// STACKIT Project ID to which the resource is associated.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The STACKIT region name the resource is located in. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetModelexperimentsInstanceInvokeArgs()
        {
        }
        public static new GetModelexperimentsInstanceInvokeArgs Empty => new GetModelexperimentsInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetModelexperimentsInstanceResult
    {
        /// <summary>
        /// The object storage bucket name of the AI Model Experiments instance.
        /// </summary>
        public readonly string BucketName;
        /// <summary>
        /// The deleted experiment retention time of the AI Model Experiments instance.
        /// </summary>
        public readonly string DeletedExperimentRetention;
        /// <summary>
        /// The description is a longer text chosen by the user to provide more context for the resource.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Terraform's internal resource identifier. It is structured as "`ProjectId`,`Region`,`InstanceId`".
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The AI Model Experiments instance ID.
        /// </summary>
        public readonly string InstanceId;
        /// <summary>
        /// A map of arbitrary key/value pairs that can be attached to the resource
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// The display name is a short name chosen by the user to identify the resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// STACKIT Project ID to which the resource is associated.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The STACKIT region name the resource is located in. If not defined, the provider region is used.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// The Dashboard URL of the AI Model Experiments instance.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetModelexperimentsInstanceResult(
            string bucketName,

            string deletedExperimentRetention,

            string description,

            string id,

            string instanceId,

            ImmutableDictionary<string, string> labels,

            string name,

            string projectId,

            string region,

            string url)
        {
            BucketName = bucketName;
            DeletedExperimentRetention = deletedExperimentRetention;
            Description = description;
            Id = id;
            InstanceId = instanceId;
            Labels = labels;
            Name = name;
            ProjectId = projectId;
            Region = region;
            Url = url;
        }
    }
}
