// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit
{
    public static class GetPostgresflexInstance
    {
        /// <summary>
        /// Postgres Flex instance data source schema. Must have a `region` specified in the provider configuration.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_postgresflex_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   instance_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Task<GetPostgresflexInstanceResult> InvokeAsync(GetPostgresflexInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPostgresflexInstanceResult>("stackit:index/getPostgresflexInstance:getPostgresflexInstance", args ?? new GetPostgresflexInstanceArgs(), options.WithDefaults());

        /// <summary>
        /// Postgres Flex instance data source schema. Must have a `region` specified in the provider configuration.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_postgresflex_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   instance_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Output<GetPostgresflexInstanceResult> Invoke(GetPostgresflexInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostgresflexInstanceResult>("stackit:index/getPostgresflexInstance:getPostgresflexInstance", args ?? new GetPostgresflexInstanceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Postgres Flex instance data source schema. Must have a `region` specified in the provider configuration.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_postgresflex_instance" "example" {
        ///   project_id  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        ///   instance_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Output<GetPostgresflexInstanceResult> Invoke(GetPostgresflexInstanceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostgresflexInstanceResult>("stackit:index/getPostgresflexInstance:getPostgresflexInstance", args ?? new GetPostgresflexInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPostgresflexInstanceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the PostgresFlex instance.
        /// </summary>
        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        /// <summary>
        /// STACKIT project ID to which the instance is associated.
        /// </summary>
        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        public GetPostgresflexInstanceArgs()
        {
        }
        public static new GetPostgresflexInstanceArgs Empty => new GetPostgresflexInstanceArgs();
    }

    public sealed class GetPostgresflexInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the PostgresFlex instance.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        /// <summary>
        /// STACKIT project ID to which the instance is associated.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetPostgresflexInstanceInvokeArgs()
        {
        }
        public static new GetPostgresflexInstanceInvokeArgs Empty => new GetPostgresflexInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetPostgresflexInstanceResult
    {
        /// <summary>
        /// The Access Control List (ACL) for the PostgresFlex instance.
        /// </summary>
        public readonly ImmutableArray<string> Acls;
        public readonly string BackupSchedule;
        public readonly Outputs.GetPostgresflexInstanceFlavorResult Flavor;
        public readonly string Id;
        /// <summary>
        /// ID of the PostgresFlex instance.
        /// </summary>
        public readonly string InstanceId;
        /// <summary>
        /// Instance name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// STACKIT project ID to which the instance is associated.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        public readonly string? Region;
        public readonly int Replicas;
        public readonly Outputs.GetPostgresflexInstanceStorageResult Storage;
        public readonly string Version;

        [OutputConstructor]
        private GetPostgresflexInstanceResult(
            ImmutableArray<string> acls,

            string backupSchedule,

            Outputs.GetPostgresflexInstanceFlavorResult flavor,

            string id,

            string instanceId,

            string name,

            string projectId,

            string? region,

            int replicas,

            Outputs.GetPostgresflexInstanceStorageResult storage,

            string version)
        {
            Acls = acls;
            BackupSchedule = backupSchedule;
            Flavor = flavor;
            Id = id;
            InstanceId = instanceId;
            Name = name;
            ProjectId = projectId;
            Region = region;
            Replicas = replicas;
            Storage = storage;
            Version = version;
        }
    }
}
