// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit
{
    public static class GetSecretsmanagerSecretGroupRoleBindingsV1
    {
        /// <summary>
        /// IAM role binding datasource schema.
        /// 
        /// &gt; This datasource is part of the iam experiment and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_secretsmanager_secret_group_role_bindings_v1" "role_binding" {
        ///   resource_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Task<GetSecretsmanagerSecretGroupRoleBindingsV1Result> InvokeAsync(GetSecretsmanagerSecretGroupRoleBindingsV1Args args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSecretsmanagerSecretGroupRoleBindingsV1Result>("stackit:index/getSecretsmanagerSecretGroupRoleBindingsV1:getSecretsmanagerSecretGroupRoleBindingsV1", args ?? new GetSecretsmanagerSecretGroupRoleBindingsV1Args(), options.WithDefaults());

        /// <summary>
        /// IAM role binding datasource schema.
        /// 
        /// &gt; This datasource is part of the iam experiment and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_secretsmanager_secret_group_role_bindings_v1" "role_binding" {
        ///   resource_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Output<GetSecretsmanagerSecretGroupRoleBindingsV1Result> Invoke(GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsmanagerSecretGroupRoleBindingsV1Result>("stackit:index/getSecretsmanagerSecretGroupRoleBindingsV1:getSecretsmanagerSecretGroupRoleBindingsV1", args ?? new GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// IAM role binding datasource schema.
        /// 
        /// &gt; This datasource is part of the iam experiment and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// data "stackit_secretsmanager_secret_group_role_bindings_v1" "role_binding" {
        ///   resource_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        /// }
        /// ```
        /// </summary>
        public static Output<GetSecretsmanagerSecretGroupRoleBindingsV1Result> Invoke(GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsmanagerSecretGroupRoleBindingsV1Result>("stackit:index/getSecretsmanagerSecretGroupRoleBindingsV1:getSecretsmanagerSecretGroupRoleBindingsV1", args ?? new GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSecretsmanagerSecretGroupRoleBindingsV1Args : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        /// <summary>
        /// The identifier of the resource to get the role bindings for.
        /// </summary>
        [Input("resourceId", required: true)]
        public string ResourceId { get; set; } = null!;

        public GetSecretsmanagerSecretGroupRoleBindingsV1Args()
        {
        }
        public static new GetSecretsmanagerSecretGroupRoleBindingsV1Args Empty => new GetSecretsmanagerSecretGroupRoleBindingsV1Args();
    }

    public sealed class GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The identifier of the resource to get the role bindings for.
        /// </summary>
        [Input("resourceId", required: true)]
        public Input<string> ResourceId { get; set; } = null!;

        public GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs()
        {
        }
        public static new GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs Empty => new GetSecretsmanagerSecretGroupRoleBindingsV1InvokeArgs();
    }


    [OutputType]
    public sealed class GetSecretsmanagerSecretGroupRoleBindingsV1Result
    {
        /// <summary>
        /// Terraform's internal resource identifier. It is structured as "`Region`,`ResourceId`".
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// The identifier of the resource to get the role bindings for.
        /// </summary>
        public readonly string ResourceId;
        /// <summary>
        /// List of role bindings.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSecretsmanagerSecretGroupRoleBindingsV1RoleBindingResult> RoleBindings;

        [OutputConstructor]
        private GetSecretsmanagerSecretGroupRoleBindingsV1Result(
            string id,

            string? region,

            string resourceId,

            ImmutableArray<Outputs.GetSecretsmanagerSecretGroupRoleBindingsV1RoleBindingResult> roleBindings)
        {
            Id = id;
            Region = region;
            ResourceId = resourceId;
            RoleBindings = roleBindings;
        }
    }
}
