// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit
{
    /// <summary>
    /// SFS project lock resource schema. Must have a `Region` specified in the provider configuration. Always use only one project lock per project.
    /// 
    /// ## Example Usage
    /// </summary>
    [StackitResourceType("stackit:index/sfsProjectLock:SfsProjectLock")]
    public partial class SfsProjectLock : global::Pulumi.CustomResource
    {
        /// <summary>
        /// ID of the lock.
        /// </summary>
        [Output("lockId")]
        public Output<string> LockId { get; private set; } = null!;

        /// <summary>
        /// STACKIT Project ID to which the project lock is associated.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a SfsProjectLock resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SfsProjectLock(string name, SfsProjectLockArgs args, CustomResourceOptions? options = null)
            : base("stackit:index/sfsProjectLock:SfsProjectLock", name, args ?? new SfsProjectLockArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SfsProjectLock(string name, Input<string> id, SfsProjectLockState? state = null, CustomResourceOptions? options = null)
            : base("stackit:index/sfsProjectLock:SfsProjectLock", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/stackitcloud/pulumi-stackit",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SfsProjectLock resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SfsProjectLock Get(string name, Input<string> id, SfsProjectLockState? state = null, CustomResourceOptions? options = null)
        {
            return new SfsProjectLock(name, id, state, options);
        }
    }

    public sealed class SfsProjectLockArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// STACKIT Project ID to which the project lock is associated.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public SfsProjectLockArgs()
        {
        }
        public static new SfsProjectLockArgs Empty => new SfsProjectLockArgs();
    }

    public sealed class SfsProjectLockState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the lock.
        /// </summary>
        [Input("lockId")]
        public Input<string>? LockId { get; set; }

        /// <summary>
        /// STACKIT Project ID to which the project lock is associated.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// The resource region. If not defined, the provider region is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public SfsProjectLockState()
        {
        }
        public static new SfsProjectLockState Empty => new SfsProjectLockState();
    }
}
