# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApplicationLoadBalancerArgs', 'ApplicationLoadBalancer']

@pulumi.input_type
class ApplicationLoadBalancerArgs:
    def __init__(__self__, *,
                 listeners: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]],
                 networks: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]],
                 plan_id: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 target_pools: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]],
                 disable_target_security_group_assignment: Optional[pulumi.Input[_builtins.bool]] = None,
                 external_address: Optional[pulumi.Input[_builtins.str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 options: Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApplicationLoadBalancer resource.

        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]] listeners: List of all listeners which will accept traffic. Limited to 20.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]] networks: List of networks that listeners and targets reside in.
        :param pulumi.Input[_builtins.str] plan_id: Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the Application Load Balancer is associated.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]] target_pools: List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        :param pulumi.Input[_builtins.bool] disable_target_security_group_assignment: Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        :param pulumi.Input[_builtins.str] external_address: The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        :param pulumi.Input[_builtins.str] name: Application Load balancer name.
        :param pulumi.Input['ApplicationLoadBalancerOptionsArgs'] options: Defines any optional functionality you want to have enabled on your Application Load Balancer.
        :param pulumi.Input[_builtins.str] region: The resource region (e.g. eu01). If not defined, the provider region is used.
        """
        pulumi.set(__self__, "listeners", listeners)
        pulumi.set(__self__, "networks", networks)
        pulumi.set(__self__, "plan_id", plan_id)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "target_pools", target_pools)
        if disable_target_security_group_assignment is not None:
            pulumi.set(__self__, "disable_target_security_group_assignment", disable_target_security_group_assignment)
        if external_address is not None:
            pulumi.set(__self__, "external_address", external_address)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if options is not None:
            pulumi.set(__self__, "options", options)
        if region is not None:
            pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter
    def listeners(self) -> pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]]:
        """
        List of all listeners which will accept traffic. Limited to 20.
        """
        return pulumi.get(self, "listeners")

    @listeners.setter
    def listeners(self, value: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]]):
        pulumi.set(self, "listeners", value)

    @_builtins.property
    @pulumi.getter
    def networks(self) -> pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]]:
        """
        List of networks that listeners and targets reside in.
        """
        return pulumi.get(self, "networks")

    @networks.setter
    def networks(self, value: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]]):
        pulumi.set(self, "networks", value)

    @_builtins.property
    @pulumi.getter(name="planId")
    def plan_id(self) -> pulumi.Input[_builtins.str]:
        """
        Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        """
        return pulumi.get(self, "plan_id")

    @plan_id.setter
    def plan_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "plan_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        STACKIT project ID to which the Application Load Balancer is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="targetPools")
    def target_pools(self) -> pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]]:
        """
        List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        """
        return pulumi.get(self, "target_pools")

    @target_pools.setter
    def target_pools(self, value: pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]]):
        pulumi.set(self, "target_pools", value)

    @_builtins.property
    @pulumi.getter(name="disableTargetSecurityGroupAssignment")
    def disable_target_security_group_assignment(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        """
        return pulumi.get(self, "disable_target_security_group_assignment")

    @disable_target_security_group_assignment.setter
    def disable_target_security_group_assignment(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disable_target_security_group_assignment", value)

    @_builtins.property
    @pulumi.getter(name="externalAddress")
    def external_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        """
        return pulumi.get(self, "external_address")

    @external_address.setter
    def external_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "external_address", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Application Load balancer name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def options(self) -> Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']]:
        """
        Defines any optional functionality you want to have enabled on your Application Load Balancer.
        """
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']]):
        pulumi.set(self, "options", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The resource region (e.g. eu01). If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)


@pulumi.input_type
class _ApplicationLoadBalancerState:
    def __init__(__self__, *,
                 disable_target_security_group_assignment: Optional[pulumi.Input[_builtins.bool]] = None,
                 errors: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerErrorArgs']]]] = None,
                 external_address: Optional[pulumi.Input[_builtins.str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 listeners: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]]] = None,
                 load_balancer_security_group: Optional[pulumi.Input['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 networks: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]]] = None,
                 options: Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']] = None,
                 plan_id: Optional[pulumi.Input[_builtins.str]] = None,
                 private_address: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 target_pools: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]]] = None,
                 target_security_group: Optional[pulumi.Input['ApplicationLoadBalancerTargetSecurityGroupArgs']] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ApplicationLoadBalancer resources.

        :param pulumi.Input[_builtins.bool] disable_target_security_group_assignment: Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerErrorArgs']]] errors: Reports all errors a Application Load Balancer has.
        :param pulumi.Input[_builtins.str] external_address: The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]] listeners: List of all listeners which will accept traffic. Limited to 20.
        :param pulumi.Input['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs'] load_balancer_security_group: Security Group permitting network traffic from the LoadBalancer to the targets. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        :param pulumi.Input[_builtins.str] name: Application Load balancer name.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]] networks: List of networks that listeners and targets reside in.
        :param pulumi.Input['ApplicationLoadBalancerOptionsArgs'] options: Defines any optional functionality you want to have enabled on your Application Load Balancer.
        :param pulumi.Input[_builtins.str] plan_id: Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the Application Load Balancer is associated.
        :param pulumi.Input[_builtins.str] region: The resource region (e.g. eu01). If not defined, the provider region is used.
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]] target_pools: List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        :param pulumi.Input['ApplicationLoadBalancerTargetSecurityGroupArgs'] target_security_group: Security Group that allows the targets to receive traffic from the LoadBalancer. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        :param pulumi.Input[_builtins.str] version: Application Load Balancer resource version. Used for concurrency safe updates.
        """
        if disable_target_security_group_assignment is not None:
            pulumi.set(__self__, "disable_target_security_group_assignment", disable_target_security_group_assignment)
        if errors is not None:
            pulumi.set(__self__, "errors", errors)
        if external_address is not None:
            pulumi.set(__self__, "external_address", external_address)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if listeners is not None:
            pulumi.set(__self__, "listeners", listeners)
        if load_balancer_security_group is not None:
            pulumi.set(__self__, "load_balancer_security_group", load_balancer_security_group)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if networks is not None:
            pulumi.set(__self__, "networks", networks)
        if options is not None:
            pulumi.set(__self__, "options", options)
        if plan_id is not None:
            pulumi.set(__self__, "plan_id", plan_id)
        if private_address is not None:
            pulumi.set(__self__, "private_address", private_address)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if target_pools is not None:
            pulumi.set(__self__, "target_pools", target_pools)
        if target_security_group is not None:
            pulumi.set(__self__, "target_security_group", target_security_group)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="disableTargetSecurityGroupAssignment")
    def disable_target_security_group_assignment(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        """
        return pulumi.get(self, "disable_target_security_group_assignment")

    @disable_target_security_group_assignment.setter
    def disable_target_security_group_assignment(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disable_target_security_group_assignment", value)

    @_builtins.property
    @pulumi.getter
    def errors(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerErrorArgs']]]]:
        """
        Reports all errors a Application Load Balancer has.
        """
        return pulumi.get(self, "errors")

    @errors.setter
    def errors(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerErrorArgs']]]]):
        pulumi.set(self, "errors", value)

    @_builtins.property
    @pulumi.getter(name="externalAddress")
    def external_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        """
        return pulumi.get(self, "external_address")

    @external_address.setter
    def external_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "external_address", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def listeners(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]]]:
        """
        List of all listeners which will accept traffic. Limited to 20.
        """
        return pulumi.get(self, "listeners")

    @listeners.setter
    def listeners(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerListenerArgs']]]]):
        pulumi.set(self, "listeners", value)

    @_builtins.property
    @pulumi.getter(name="loadBalancerSecurityGroup")
    def load_balancer_security_group(self) -> Optional[pulumi.Input['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs']]:
        """
        Security Group permitting network traffic from the LoadBalancer to the targets. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        """
        return pulumi.get(self, "load_balancer_security_group")

    @load_balancer_security_group.setter
    def load_balancer_security_group(self, value: Optional[pulumi.Input['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs']]):
        pulumi.set(self, "load_balancer_security_group", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Application Load balancer name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def networks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]]]:
        """
        List of networks that listeners and targets reside in.
        """
        return pulumi.get(self, "networks")

    @networks.setter
    def networks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerNetworkArgs']]]]):
        pulumi.set(self, "networks", value)

    @_builtins.property
    @pulumi.getter
    def options(self) -> Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']]:
        """
        Defines any optional functionality you want to have enabled on your Application Load Balancer.
        """
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: Optional[pulumi.Input['ApplicationLoadBalancerOptionsArgs']]):
        pulumi.set(self, "options", value)

    @_builtins.property
    @pulumi.getter(name="planId")
    def plan_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        """
        return pulumi.get(self, "plan_id")

    @plan_id.setter
    def plan_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "plan_id", value)

    @_builtins.property
    @pulumi.getter(name="privateAddress")
    def private_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "private_address")

    @private_address.setter
    def private_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "private_address", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        STACKIT project ID to which the Application Load Balancer is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The resource region (e.g. eu01). If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="targetPools")
    def target_pools(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]]]:
        """
        List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        """
        return pulumi.get(self, "target_pools")

    @target_pools.setter
    def target_pools(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ApplicationLoadBalancerTargetPoolArgs']]]]):
        pulumi.set(self, "target_pools", value)

    @_builtins.property
    @pulumi.getter(name="targetSecurityGroup")
    def target_security_group(self) -> Optional[pulumi.Input['ApplicationLoadBalancerTargetSecurityGroupArgs']]:
        """
        Security Group that allows the targets to receive traffic from the LoadBalancer. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        """
        return pulumi.get(self, "target_security_group")

    @target_security_group.setter
    def target_security_group(self, value: Optional[pulumi.Input['ApplicationLoadBalancerTargetSecurityGroupArgs']]):
        pulumi.set(self, "target_security_group", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Application Load Balancer resource version. Used for concurrency safe updates.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("stackit:index/applicationLoadBalancer:ApplicationLoadBalancer")
class ApplicationLoadBalancer(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 disable_target_security_group_assignment: Optional[pulumi.Input[_builtins.bool]] = None,
                 external_address: Optional[pulumi.Input[_builtins.str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 listeners: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerListenerArgs', 'ApplicationLoadBalancerListenerArgsDict']]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 networks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerNetworkArgs', 'ApplicationLoadBalancerNetworkArgsDict']]]]] = None,
                 options: Optional[pulumi.Input[Union['ApplicationLoadBalancerOptionsArgs', 'ApplicationLoadBalancerOptionsArgsDict']]] = None,
                 plan_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 target_pools: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerTargetPoolArgs', 'ApplicationLoadBalancerTargetPoolArgsDict']]]]] = None,
                 __props__=None):
        """
        ## Setting up supporting infrastructure

        The example below creates the supporting infrastructure using the STACKIT Terraform provider, including the network, network interface, a public IP address and server resources.

        ## Example Usage


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] disable_target_security_group_assignment: Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        :param pulumi.Input[_builtins.str] external_address: The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerListenerArgs', 'ApplicationLoadBalancerListenerArgsDict']]]] listeners: List of all listeners which will accept traffic. Limited to 20.
        :param pulumi.Input[_builtins.str] name: Application Load balancer name.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerNetworkArgs', 'ApplicationLoadBalancerNetworkArgsDict']]]] networks: List of networks that listeners and targets reside in.
        :param pulumi.Input[Union['ApplicationLoadBalancerOptionsArgs', 'ApplicationLoadBalancerOptionsArgsDict']] options: Defines any optional functionality you want to have enabled on your Application Load Balancer.
        :param pulumi.Input[_builtins.str] plan_id: Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the Application Load Balancer is associated.
        :param pulumi.Input[_builtins.str] region: The resource region (e.g. eu01). If not defined, the provider region is used.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerTargetPoolArgs', 'ApplicationLoadBalancerTargetPoolArgsDict']]]] target_pools: List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationLoadBalancerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Setting up supporting infrastructure

        The example below creates the supporting infrastructure using the STACKIT Terraform provider, including the network, network interface, a public IP address and server resources.

        ## Example Usage


        :param str resource_name: The name of the resource.
        :param ApplicationLoadBalancerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationLoadBalancerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 disable_target_security_group_assignment: Optional[pulumi.Input[_builtins.bool]] = None,
                 external_address: Optional[pulumi.Input[_builtins.str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 listeners: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerListenerArgs', 'ApplicationLoadBalancerListenerArgsDict']]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 networks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerNetworkArgs', 'ApplicationLoadBalancerNetworkArgsDict']]]]] = None,
                 options: Optional[pulumi.Input[Union['ApplicationLoadBalancerOptionsArgs', 'ApplicationLoadBalancerOptionsArgsDict']]] = None,
                 plan_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 target_pools: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerTargetPoolArgs', 'ApplicationLoadBalancerTargetPoolArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationLoadBalancerArgs.__new__(ApplicationLoadBalancerArgs)

            __props__.__dict__["disable_target_security_group_assignment"] = disable_target_security_group_assignment
            __props__.__dict__["external_address"] = external_address
            __props__.__dict__["labels"] = labels
            if listeners is None and not opts.urn:
                raise TypeError("Missing required property 'listeners'")
            __props__.__dict__["listeners"] = listeners
            __props__.__dict__["name"] = name
            if networks is None and not opts.urn:
                raise TypeError("Missing required property 'networks'")
            __props__.__dict__["networks"] = networks
            __props__.__dict__["options"] = options
            if plan_id is None and not opts.urn:
                raise TypeError("Missing required property 'plan_id'")
            __props__.__dict__["plan_id"] = plan_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["region"] = region
            if target_pools is None and not opts.urn:
                raise TypeError("Missing required property 'target_pools'")
            __props__.__dict__["target_pools"] = target_pools
            __props__.__dict__["errors"] = None
            __props__.__dict__["load_balancer_security_group"] = None
            __props__.__dict__["private_address"] = None
            __props__.__dict__["target_security_group"] = None
            __props__.__dict__["version"] = None
        super(ApplicationLoadBalancer, __self__).__init__(
            'stackit:index/applicationLoadBalancer:ApplicationLoadBalancer',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            disable_target_security_group_assignment: Optional[pulumi.Input[_builtins.bool]] = None,
            errors: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerErrorArgs', 'ApplicationLoadBalancerErrorArgsDict']]]]] = None,
            external_address: Optional[pulumi.Input[_builtins.str]] = None,
            labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            listeners: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerListenerArgs', 'ApplicationLoadBalancerListenerArgsDict']]]]] = None,
            load_balancer_security_group: Optional[pulumi.Input[Union['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs', 'ApplicationLoadBalancerLoadBalancerSecurityGroupArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            networks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerNetworkArgs', 'ApplicationLoadBalancerNetworkArgsDict']]]]] = None,
            options: Optional[pulumi.Input[Union['ApplicationLoadBalancerOptionsArgs', 'ApplicationLoadBalancerOptionsArgsDict']]] = None,
            plan_id: Optional[pulumi.Input[_builtins.str]] = None,
            private_address: Optional[pulumi.Input[_builtins.str]] = None,
            project_id: Optional[pulumi.Input[_builtins.str]] = None,
            region: Optional[pulumi.Input[_builtins.str]] = None,
            target_pools: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerTargetPoolArgs', 'ApplicationLoadBalancerTargetPoolArgsDict']]]]] = None,
            target_security_group: Optional[pulumi.Input[Union['ApplicationLoadBalancerTargetSecurityGroupArgs', 'ApplicationLoadBalancerTargetSecurityGroupArgsDict']]] = None,
            version: Optional[pulumi.Input[_builtins.str]] = None) -> 'ApplicationLoadBalancer':
        """
        Get an existing ApplicationLoadBalancer resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] disable_target_security_group_assignment: Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerErrorArgs', 'ApplicationLoadBalancerErrorArgsDict']]]] errors: Reports all errors a Application Load Balancer has.
        :param pulumi.Input[_builtins.str] external_address: The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerListenerArgs', 'ApplicationLoadBalancerListenerArgsDict']]]] listeners: List of all listeners which will accept traffic. Limited to 20.
        :param pulumi.Input[Union['ApplicationLoadBalancerLoadBalancerSecurityGroupArgs', 'ApplicationLoadBalancerLoadBalancerSecurityGroupArgsDict']] load_balancer_security_group: Security Group permitting network traffic from the LoadBalancer to the targets. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        :param pulumi.Input[_builtins.str] name: Application Load balancer name.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerNetworkArgs', 'ApplicationLoadBalancerNetworkArgsDict']]]] networks: List of networks that listeners and targets reside in.
        :param pulumi.Input[Union['ApplicationLoadBalancerOptionsArgs', 'ApplicationLoadBalancerOptionsArgsDict']] options: Defines any optional functionality you want to have enabled on your Application Load Balancer.
        :param pulumi.Input[_builtins.str] plan_id: Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the Application Load Balancer is associated.
        :param pulumi.Input[_builtins.str] region: The resource region (e.g. eu01). If not defined, the provider region is used.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationLoadBalancerTargetPoolArgs', 'ApplicationLoadBalancerTargetPoolArgsDict']]]] target_pools: List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        :param pulumi.Input[Union['ApplicationLoadBalancerTargetSecurityGroupArgs', 'ApplicationLoadBalancerTargetSecurityGroupArgsDict']] target_security_group: Security Group that allows the targets to receive traffic from the LoadBalancer. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        :param pulumi.Input[_builtins.str] version: Application Load Balancer resource version. Used for concurrency safe updates.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApplicationLoadBalancerState.__new__(_ApplicationLoadBalancerState)

        __props__.__dict__["disable_target_security_group_assignment"] = disable_target_security_group_assignment
        __props__.__dict__["errors"] = errors
        __props__.__dict__["external_address"] = external_address
        __props__.__dict__["labels"] = labels
        __props__.__dict__["listeners"] = listeners
        __props__.__dict__["load_balancer_security_group"] = load_balancer_security_group
        __props__.__dict__["name"] = name
        __props__.__dict__["networks"] = networks
        __props__.__dict__["options"] = options
        __props__.__dict__["plan_id"] = plan_id
        __props__.__dict__["private_address"] = private_address
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["region"] = region
        __props__.__dict__["target_pools"] = target_pools
        __props__.__dict__["target_security_group"] = target_security_group
        __props__.__dict__["version"] = version
        return ApplicationLoadBalancer(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="disableTargetSecurityGroupAssignment")
    def disable_target_security_group_assignment(self) -> pulumi.Output[_builtins.bool]:
        """
        Disable target security group assignemt to allow targets outside of the given network. Connectivity to targets need to be ensured by the customer, including routing and Security Groups (targetSecurityGroup can be assigned). Not changeable after creation.
        """
        return pulumi.get(self, "disable_target_security_group_assignment")

    @_builtins.property
    @pulumi.getter
    def errors(self) -> pulumi.Output[Sequence['outputs.ApplicationLoadBalancerError']]:
        """
        Reports all errors a Application Load Balancer has.
        """
        return pulumi.get(self, "errors")

    @_builtins.property
    @pulumi.getter(name="externalAddress")
    def external_address(self) -> pulumi.Output[_builtins.str]:
        """
        The external IP address where this Application Load Balancer is exposed. Not changeable after creation.
        """
        return pulumi.get(self, "external_address")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels represent user-defined metadata as key-value pairs. Label count cannot exceed 64 per ALB.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def listeners(self) -> pulumi.Output[Sequence['outputs.ApplicationLoadBalancerListener']]:
        """
        List of all listeners which will accept traffic. Limited to 20.
        """
        return pulumi.get(self, "listeners")

    @_builtins.property
    @pulumi.getter(name="loadBalancerSecurityGroup")
    def load_balancer_security_group(self) -> pulumi.Output['outputs.ApplicationLoadBalancerLoadBalancerSecurityGroup']:
        """
        Security Group permitting network traffic from the LoadBalancer to the targets. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        """
        return pulumi.get(self, "load_balancer_security_group")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Application Load balancer name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def networks(self) -> pulumi.Output[Sequence['outputs.ApplicationLoadBalancerNetwork']]:
        """
        List of networks that listeners and targets reside in.
        """
        return pulumi.get(self, "networks")

    @_builtins.property
    @pulumi.getter
    def options(self) -> pulumi.Output[Optional['outputs.ApplicationLoadBalancerOptions']]:
        """
        Defines any optional functionality you want to have enabled on your Application Load Balancer.
        """
        return pulumi.get(self, "options")

    @_builtins.property
    @pulumi.getter(name="planId")
    def plan_id(self) -> pulumi.Output[_builtins.str]:
        """
        Service Plan configures the size of the Application Load Balancer e.g. 'p10'. See available plans via STACKIT CLI 'stackit beta alb plans' or API https://docs.api.stackit.cloud/documentation/alb/version/v2#tag/Project/operation/APIService_ListPlans
        """
        return pulumi.get(self, "plan_id")

    @_builtins.property
    @pulumi.getter(name="privateAddress")
    def private_address(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "private_address")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        STACKIT project ID to which the Application Load Balancer is associated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        The resource region (e.g. eu01). If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="targetPools")
    def target_pools(self) -> pulumi.Output[Sequence['outputs.ApplicationLoadBalancerTargetPool']]:
        """
        List of all target pools which will be used in the Application Load Balancer. Limited to 20.
        """
        return pulumi.get(self, "target_pools")

    @_builtins.property
    @pulumi.getter(name="targetSecurityGroup")
    def target_security_group(self) -> pulumi.Output['outputs.ApplicationLoadBalancerTargetSecurityGroup']:
        """
        Security Group that allows the targets to receive traffic from the LoadBalancer. Useful when disableTargetSecurityGroupAssignment=true to manually assign target security groups to targets.
        """
        return pulumi.get(self, "target_security_group")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Application Load Balancer resource version. Used for concurrency safe updates.
        """
        return pulumi.get(self, "version")

