# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['DremioInstanceArgs', 'DremioInstance']

@pulumi.input_type
class DremioInstanceArgs:
    def __init__(__self__, *,
                 authentication: pulumi.Input['DremioInstanceAuthenticationArgs'],
                 display_name: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 timeouts: pulumi.Input[Optional['DremioInstanceTimeoutsArgs']] = None):
        """
        The set of arguments for constructing a DremioInstance resource.

        :param pulumi.Input['DremioInstanceAuthenticationArgs'] authentication: Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        :param pulumi.Input[_builtins.str] display_name: The display name is a short name chosen by the user to identify the resource.
        :param pulumi.Input[_builtins.str] project_id: STACKIT Project ID to which the resource is associated.
        :param pulumi.Input[_builtins.str] description: The description is a longer text chosen by the user to provide more context for the resource.
        :param pulumi.Input[_builtins.str] region: The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        pulumi.set(__self__, "authentication", authentication)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "project_id", project_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter
    def authentication(self) -> pulumi.Input['DremioInstanceAuthenticationArgs']:
        """
        Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        """
        return pulumi.get(self, "authentication")

    @authentication.setter
    def authentication(self, value: pulumi.Input['DremioInstanceAuthenticationArgs']):
        pulumi.set(self, "authentication", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        The display name is a short name chosen by the user to identify the resource.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        STACKIT Project ID to which the resource is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description is a longer text chosen by the user to provide more context for the resource.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Input[Optional['DremioInstanceTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: pulumi.Input[Optional['DremioInstanceTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.input_type
class _DremioInstanceState:
    def __init__(__self__, *,
                 authentication: pulumi.Input[Optional['DremioInstanceAuthenticationArgs']] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoints: pulumi.Input[Optional['DremioInstanceEndpointsArgs']] = None,
                 instance_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 timeouts: pulumi.Input[Optional['DremioInstanceTimeoutsArgs']] = None):
        """
        Input properties used for looking up and filtering DremioInstance resources.

        :param pulumi.Input['DremioInstanceAuthenticationArgs'] authentication: Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        :param pulumi.Input[_builtins.str] description: The description is a longer text chosen by the user to provide more context for the resource.
        :param pulumi.Input[_builtins.str] display_name: The display name is a short name chosen by the user to identify the resource.
        :param pulumi.Input['DremioInstanceEndpointsArgs'] endpoints: The available endpoints of the Dremio instance.
        :param pulumi.Input[_builtins.str] instance_id: The Dremio instance ID.
        :param pulumi.Input[_builtins.str] project_id: STACKIT Project ID to which the resource is associated.
        :param pulumi.Input[_builtins.str] region: The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        if authentication is not None:
            pulumi.set(__self__, "authentication", authentication)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if instance_id is not None:
            pulumi.set(__self__, "instance_id", instance_id)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter
    def authentication(self) -> pulumi.Input[Optional['DremioInstanceAuthenticationArgs']]:
        """
        Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        """
        return pulumi.get(self, "authentication")

    @authentication.setter
    def authentication(self, value: pulumi.Input[Optional['DremioInstanceAuthenticationArgs']]):
        pulumi.set(self, "authentication", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description is a longer text chosen by the user to provide more context for the resource.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The display name is a short name chosen by the user to identify the resource.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Input[Optional['DremioInstanceEndpointsArgs']]:
        """
        The available endpoints of the Dremio instance.
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: pulumi.Input[Optional['DremioInstanceEndpointsArgs']]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The Dremio instance ID.
        """
        return pulumi.get(self, "instance_id")

    @instance_id.setter
    def instance_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "instance_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        STACKIT Project ID to which the resource is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Input[Optional['DremioInstanceTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: pulumi.Input[Optional['DremioInstanceTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.type_token("stackit:index/dremioInstance:DremioInstance")
class DremioInstance(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 authentication: pulumi.Input[Optional[Union['DremioInstanceAuthenticationArgs', 'DremioInstanceAuthenticationArgsDict']]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 timeouts: pulumi.Input[Optional[Union['DremioInstanceTimeoutsArgs', 'DremioInstanceTimeoutsArgsDict']]] = None,
                 __props__=None):
        """
        Manages a STACKIT Dremio instance.

        > This resource is part of the experimental feature dremio and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.

        ## Example Usage

        ## Import

        In Terraform v1.5.0 and later, the `  + " `" + `import` + "` " +  ` block can be used with the `  + " `" + `id` + "` " +  ` attribute, for example:


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['DremioInstanceAuthenticationArgs', 'DremioInstanceAuthenticationArgsDict']] authentication: Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        :param pulumi.Input[_builtins.str] description: The description is a longer text chosen by the user to provide more context for the resource.
        :param pulumi.Input[_builtins.str] display_name: The display name is a short name chosen by the user to identify the resource.
        :param pulumi.Input[_builtins.str] project_id: STACKIT Project ID to which the resource is associated.
        :param pulumi.Input[_builtins.str] region: The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DremioInstanceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a STACKIT Dremio instance.

        > This resource is part of the experimental feature dremio and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.

        ## Example Usage

        ## Import

        In Terraform v1.5.0 and later, the `  + " `" + `import` + "` " +  ` block can be used with the `  + " `" + `id` + "` " +  ` attribute, for example:


        :param str resource_name: The name of the resource.
        :param DremioInstanceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DremioInstanceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 authentication: pulumi.Input[Optional[Union['DremioInstanceAuthenticationArgs', 'DremioInstanceAuthenticationArgsDict']]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 timeouts: pulumi.Input[Optional[Union['DremioInstanceTimeoutsArgs', 'DremioInstanceTimeoutsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DremioInstanceArgs.__new__(DremioInstanceArgs)

            if authentication is None and not opts.urn:
                raise TypeError("Missing required property 'authentication'")
            __props__.__dict__["authentication"] = authentication
            __props__.__dict__["description"] = description
            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["region"] = region
            __props__.__dict__["timeouts"] = timeouts
            __props__.__dict__["endpoints"] = None
            __props__.__dict__["instance_id"] = None
        super(DremioInstance, __self__).__init__(
            'stackit:index/dremioInstance:DremioInstance',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            authentication: pulumi.Input[Optional[Union['DremioInstanceAuthenticationArgs', 'DremioInstanceAuthenticationArgsDict']]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            display_name: pulumi.Input[Optional[_builtins.str]] = None,
            endpoints: pulumi.Input[Optional[Union['DremioInstanceEndpointsArgs', 'DremioInstanceEndpointsArgsDict']]] = None,
            instance_id: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            timeouts: pulumi.Input[Optional[Union['DremioInstanceTimeoutsArgs', 'DremioInstanceTimeoutsArgsDict']]] = None) -> 'DremioInstance':
        """
        Get an existing DremioInstance resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['DremioInstanceAuthenticationArgs', 'DremioInstanceAuthenticationArgsDict']] authentication: Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        :param pulumi.Input[_builtins.str] description: The description is a longer text chosen by the user to provide more context for the resource.
        :param pulumi.Input[_builtins.str] display_name: The display name is a short name chosen by the user to identify the resource.
        :param pulumi.Input[Union['DremioInstanceEndpointsArgs', 'DremioInstanceEndpointsArgsDict']] endpoints: The available endpoints of the Dremio instance.
        :param pulumi.Input[_builtins.str] instance_id: The Dremio instance ID.
        :param pulumi.Input[_builtins.str] project_id: STACKIT Project ID to which the resource is associated.
        :param pulumi.Input[_builtins.str] region: The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DremioInstanceState.__new__(_DremioInstanceState)

        __props__.__dict__["authentication"] = authentication
        __props__.__dict__["description"] = description
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["endpoints"] = endpoints
        __props__.__dict__["instance_id"] = instance_id
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["region"] = region
        __props__.__dict__["timeouts"] = timeouts
        return DremioInstance(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def authentication(self) -> pulumi.Output['outputs.DremioInstanceAuthentication']:
        """
        Dremio instance authentication settings. A change here triggers a Dremio restart and will incur downtime.
        """
        return pulumi.get(self, "authentication")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        The description is a longer text chosen by the user to provide more context for the resource.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name is a short name chosen by the user to identify the resource.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output['outputs.DremioInstanceEndpoints']:
        """
        The available endpoints of the Dremio instance.
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Dremio instance ID.
        """
        return pulumi.get(self, "instance_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        STACKIT Project ID to which the resource is associated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        The STACKIT region name the resource is located in. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.DremioInstanceTimeouts']]:
        return pulumi.get(self, "timeouts")

