# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetVpcRoutingTableResult',
    'AwaitableGetVpcRoutingTableResult',
    'get_vpc_routing_table',
    'get_vpc_routing_table_output',
]

@pulumi.output_type
class GetVpcRoutingTableResult:
    """
    A collection of values returned by getVpcRoutingTable.
    """
    def __init__(__self__, description=None, dynamic_routes=None, id=None, labels=None, name=None, project_id=None, region=None, routing_table_id=None, system_routes=None, vpc_id=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if dynamic_routes and not isinstance(dynamic_routes, bool):
            raise TypeError("Expected argument 'dynamic_routes' to be a bool")
        pulumi.set(__self__, "dynamic_routes", dynamic_routes)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if project_id and not isinstance(project_id, str):
            raise TypeError("Expected argument 'project_id' to be a str")
        pulumi.set(__self__, "project_id", project_id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if routing_table_id and not isinstance(routing_table_id, str):
            raise TypeError("Expected argument 'routing_table_id' to be a str")
        pulumi.set(__self__, "routing_table_id", routing_table_id)
        if system_routes and not isinstance(system_routes, bool):
            raise TypeError("Expected argument 'system_routes' to be a bool")
        pulumi.set(__self__, "system_routes", system_routes)
        if vpc_id and not isinstance(vpc_id, str):
            raise TypeError("Expected argument 'vpc_id' to be a str")
        pulumi.set(__self__, "vpc_id", vpc_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description of the regional routing table.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="dynamicRoutes")
    def dynamic_routes(self) -> _builtins.bool:
        """
        This controls whether dynamic routes are propagated to this regional routing table
        """
        return pulumi.get(self, "dynamic_routes")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Terraform's internal resource ID. It is structured as "`project_id`,`vpc_id`,`region`,`routing_table_id`".
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Labels are key-value string pairs which can be attached to a resource container
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the regional routing table.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> _builtins.str:
        """
        STACKIT project ID to which the regional routing table is associated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        The resource region. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="routingTableId")
    def routing_table_id(self) -> _builtins.str:
        """
        The regional routing tables ID.
        """
        return pulumi.get(self, "routing_table_id")

    @_builtins.property
    @pulumi.getter(name="systemRoutes")
    def system_routes(self) -> _builtins.bool:
        """
        This allows installation of automatic system routes for connectivity between projects in the same VPC.
        """
        return pulumi.get(self, "system_routes")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> _builtins.str:
        """
        The vpc ID to which the regional routing table is associated.
        """
        return pulumi.get(self, "vpc_id")


class AwaitableGetVpcRoutingTableResult(GetVpcRoutingTableResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVpcRoutingTableResult(
            description=self.description,
            dynamic_routes=self.dynamic_routes,
            id=self.id,
            labels=self.labels,
            name=self.name,
            project_id=self.project_id,
            region=self.region,
            routing_table_id=self.routing_table_id,
            system_routes=self.system_routes,
            vpc_id=self.vpc_id)


def get_vpc_routing_table(description: Optional[_builtins.str] = None,
                          dynamic_routes: Optional[_builtins.bool] = None,
                          labels: Optional[Mapping[str, _builtins.str]] = None,
                          project_id: Optional[_builtins.str] = None,
                          region: Optional[_builtins.str] = None,
                          routing_table_id: Optional[_builtins.str] = None,
                          system_routes: Optional[_builtins.bool] = None,
                          vpc_id: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVpcRoutingTableResult:
    """
    VPC Regional routing table datasource schema. Must have a `region` specified in the provider configuration.

    > This datasource is part of the experimental feature vpc and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.

    ## Example Usage


    :param _builtins.str description: Description of the regional routing table.
    :param _builtins.bool dynamic_routes: This controls whether dynamic routes are propagated to this regional routing table
    :param Mapping[str, _builtins.str] labels: Labels are key-value string pairs which can be attached to a resource container
    :param _builtins.str project_id: STACKIT project ID to which the regional routing table is associated.
    :param _builtins.str region: The resource region. If not defined, the provider region is used.
    :param _builtins.str routing_table_id: The regional routing tables ID.
    :param _builtins.bool system_routes: This allows installation of automatic system routes for connectivity between projects in the same VPC.
    :param _builtins.str vpc_id: The vpc ID to which the regional routing table is associated.
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['dynamicRoutes'] = dynamic_routes
    __args__['labels'] = labels
    __args__['projectId'] = project_id
    __args__['region'] = region
    __args__['routingTableId'] = routing_table_id
    __args__['systemRoutes'] = system_routes
    __args__['vpcId'] = vpc_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('stackit:index/getVpcRoutingTable:getVpcRoutingTable', __args__, opts=opts, typ=GetVpcRoutingTableResult).value

    return AwaitableGetVpcRoutingTableResult(
        description=pulumi.get(__ret__, 'description'),
        dynamic_routes=pulumi.get(__ret__, 'dynamic_routes'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        name=pulumi.get(__ret__, 'name'),
        project_id=pulumi.get(__ret__, 'project_id'),
        region=pulumi.get(__ret__, 'region'),
        routing_table_id=pulumi.get(__ret__, 'routing_table_id'),
        system_routes=pulumi.get(__ret__, 'system_routes'),
        vpc_id=pulumi.get(__ret__, 'vpc_id'))
def get_vpc_routing_table_output(description: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 dynamic_routes: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                                 labels: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                                 region: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 routing_table_id: pulumi.Input[Optional[_builtins.str]] = None,
                                 system_routes: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                                 vpc_id: pulumi.Input[Optional[_builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetVpcRoutingTableResult]:
    """
    VPC Regional routing table datasource schema. Must have a `region` specified in the provider configuration.

    > This datasource is part of the experimental feature vpc and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.

    ## Example Usage


    :param _builtins.str description: Description of the regional routing table.
    :param _builtins.bool dynamic_routes: This controls whether dynamic routes are propagated to this regional routing table
    :param Mapping[str, _builtins.str] labels: Labels are key-value string pairs which can be attached to a resource container
    :param _builtins.str project_id: STACKIT project ID to which the regional routing table is associated.
    :param _builtins.str region: The resource region. If not defined, the provider region is used.
    :param _builtins.str routing_table_id: The regional routing tables ID.
    :param _builtins.bool system_routes: This allows installation of automatic system routes for connectivity between projects in the same VPC.
    :param _builtins.str vpc_id: The vpc ID to which the regional routing table is associated.
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['dynamicRoutes'] = dynamic_routes
    __args__['labels'] = labels
    __args__['projectId'] = project_id
    __args__['region'] = region
    __args__['routingTableId'] = routing_table_id
    __args__['systemRoutes'] = system_routes
    __args__['vpcId'] = vpc_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('stackit:index/getVpcRoutingTable:getVpcRoutingTable', __args__, opts=opts, typ=GetVpcRoutingTableResult)
    return __ret__.apply(lambda __response__: GetVpcRoutingTableResult(
        description=pulumi.get(__response__, 'description'),
        dynamic_routes=pulumi.get(__response__, 'dynamic_routes'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        name=pulumi.get(__response__, 'name'),
        project_id=pulumi.get(__response__, 'project_id'),
        region=pulumi.get(__response__, 'region'),
        routing_table_id=pulumi.get(__response__, 'routing_table_id'),
        system_routes=pulumi.get(__response__, 'system_routes'),
        vpc_id=pulumi.get(__response__, 'vpc_id')))
