# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SqlserverflexInstanceArgs', 'SqlserverflexInstance']

@pulumi.input_type
class SqlserverflexInstanceArgs:
    def __init__(__self__, *,
                 project_id: pulumi.Input[_builtins.str],
                 acls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backup_schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 flavor: pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']] = None,
                 flavor_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']] = None,
                 options: pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 storage: pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a SqlserverflexInstance resource.

        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the instance is associated.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acls: The Access Control List (ACL) for the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] backup_schedule: The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] flavor_id: The flavor ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] name: Instance name.
        :param pulumi.Input['SqlserverflexInstanceNetworkArgs'] network: The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] region: The resource region. If not defined, the provider region is used.
        :param pulumi.Input[_builtins.int] retention_days: The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input['SqlserverflexInstanceStorageArgs'] storage: The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] version: The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        pulumi.set(__self__, "project_id", project_id)
        if acls is not None:
            warnings.warn("""acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""", DeprecationWarning)
            pulumi.log.warn("""acls is deprecated: acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""")
        if acls is not None:
            pulumi.set(__self__, "acls", acls)
        if backup_schedule is not None:
            pulumi.set(__self__, "backup_schedule", backup_schedule)
        if flavor is not None:
            pulumi.set(__self__, "flavor", flavor)
        if flavor_id is not None:
            pulumi.set(__self__, "flavor_id", flavor_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network is not None:
            pulumi.set(__self__, "network", network)
        if options is not None:
            warnings.warn("""option is deprecated and will be removed after January 2027.""", DeprecationWarning)
            pulumi.log.warn("""options is deprecated: option is deprecated and will be removed after January 2027.""")
        if options is not None:
            pulumi.set(__self__, "options", options)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)
        if storage is not None:
            pulumi.set(__self__, "storage", storage)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        STACKIT project ID to which the instance is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""")
    def acls(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The Access Control List (ACL) for the SQLServer Flex instance.
        """
        return pulumi.get(self, "acls")

    @acls.setter
    def acls(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "acls", value)

    @_builtins.property
    @pulumi.getter(name="backupSchedule")
    def backup_schedule(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "backup_schedule")

    @backup_schedule.setter
    def backup_schedule(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "backup_schedule", value)

    @_builtins.property
    @pulumi.getter
    def flavor(self) -> pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']]:
        return pulumi.get(self, "flavor")

    @flavor.setter
    def flavor(self, value: pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']]):
        pulumi.set(self, "flavor", value)

    @_builtins.property
    @pulumi.getter(name="flavorId")
    def flavor_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The flavor ID of the SQLServer Flex instance.
        """
        return pulumi.get(self, "flavor_id")

    @flavor_id.setter
    def flavor_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "flavor_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Instance name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def network(self) -> pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']]:
        """
        The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "network")

    @network.setter
    def network(self, value: pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']]):
        pulumi.set(self, "network", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""option is deprecated and will be removed after January 2027.""")
    def options(self) -> pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']]:
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']]):
        pulumi.set(self, "options", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource region. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "retention_days", value)

    @_builtins.property
    @pulumi.getter
    def storage(self) -> pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']]:
        """
        The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "storage")

    @storage.setter
    def storage(self, value: pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']]):
        pulumi.set(self, "storage", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.input_type
class _SqlserverflexInstanceState:
    def __init__(__self__, *,
                 acls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backup_schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 edition: pulumi.Input[Optional[_builtins.str]] = None,
                 flavor: pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']] = None,
                 flavor_id: pulumi.Input[Optional[_builtins.str]] = None,
                 instance_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']] = None,
                 options: pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 replicas: pulumi.Input[Optional[_builtins.int]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 storage: pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SqlserverflexInstance resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acls: The Access Control List (ACL) for the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] backup_schedule: The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] edition: Edition of the MSSQL server instance.
        :param pulumi.Input[_builtins.str] flavor_id: The flavor ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] instance_id: ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] name: Instance name.
        :param pulumi.Input['SqlserverflexInstanceNetworkArgs'] network: The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the instance is associated.
        :param pulumi.Input[_builtins.str] region: The resource region. If not defined, the provider region is used.
        :param pulumi.Input[_builtins.int] retention_days: The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input['SqlserverflexInstanceStorageArgs'] storage: The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] version: The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        if acls is not None:
            warnings.warn("""acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""", DeprecationWarning)
            pulumi.log.warn("""acls is deprecated: acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""")
        if acls is not None:
            pulumi.set(__self__, "acls", acls)
        if backup_schedule is not None:
            pulumi.set(__self__, "backup_schedule", backup_schedule)
        if edition is not None:
            pulumi.set(__self__, "edition", edition)
        if flavor is not None:
            pulumi.set(__self__, "flavor", flavor)
        if flavor_id is not None:
            pulumi.set(__self__, "flavor_id", flavor_id)
        if instance_id is not None:
            pulumi.set(__self__, "instance_id", instance_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network is not None:
            pulumi.set(__self__, "network", network)
        if options is not None:
            warnings.warn("""option is deprecated and will be removed after January 2027.""", DeprecationWarning)
            pulumi.log.warn("""options is deprecated: option is deprecated and will be removed after January 2027.""")
        if options is not None:
            pulumi.set(__self__, "options", options)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if retention_days is not None:
            pulumi.set(__self__, "retention_days", retention_days)
        if storage is not None:
            pulumi.set(__self__, "storage", storage)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""")
    def acls(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The Access Control List (ACL) for the SQLServer Flex instance.
        """
        return pulumi.get(self, "acls")

    @acls.setter
    def acls(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "acls", value)

    @_builtins.property
    @pulumi.getter(name="backupSchedule")
    def backup_schedule(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "backup_schedule")

    @backup_schedule.setter
    def backup_schedule(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "backup_schedule", value)

    @_builtins.property
    @pulumi.getter
    def edition(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Edition of the MSSQL server instance.
        """
        return pulumi.get(self, "edition")

    @edition.setter
    def edition(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "edition", value)

    @_builtins.property
    @pulumi.getter
    def flavor(self) -> pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']]:
        return pulumi.get(self, "flavor")

    @flavor.setter
    def flavor(self, value: pulumi.Input[Optional['SqlserverflexInstanceFlavorArgs']]):
        pulumi.set(self, "flavor", value)

    @_builtins.property
    @pulumi.getter(name="flavorId")
    def flavor_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The flavor ID of the SQLServer Flex instance.
        """
        return pulumi.get(self, "flavor_id")

    @flavor_id.setter
    def flavor_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "flavor_id", value)

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the SQLServer Flex instance.
        """
        return pulumi.get(self, "instance_id")

    @instance_id.setter
    def instance_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "instance_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Instance name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def network(self) -> pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']]:
        """
        The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "network")

    @network.setter
    def network(self, value: pulumi.Input[Optional['SqlserverflexInstanceNetworkArgs']]):
        pulumi.set(self, "network", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""option is deprecated and will be removed after January 2027.""")
    def options(self) -> pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']]:
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: pulumi.Input[Optional['SqlserverflexInstanceOptionsArgs']]):
        pulumi.set(self, "options", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        STACKIT project ID to which the instance is associated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The resource region. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Input[Optional[_builtins.int]]:
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "retention_days")

    @retention_days.setter
    def retention_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "retention_days", value)

    @_builtins.property
    @pulumi.getter
    def storage(self) -> pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']]:
        """
        The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "storage")

    @storage.setter
    def storage(self, value: pulumi.Input[Optional['SqlserverflexInstanceStorageArgs']]):
        pulumi.set(self, "storage", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("stackit:index/sqlserverflexInstance:SqlserverflexInstance")
class SqlserverflexInstance(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backup_schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 flavor: pulumi.Input[Optional[Union['SqlserverflexInstanceFlavorArgs', 'SqlserverflexInstanceFlavorArgsDict']]] = None,
                 flavor_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional[Union['SqlserverflexInstanceNetworkArgs', 'SqlserverflexInstanceNetworkArgsDict']]] = None,
                 options: pulumi.Input[Optional[Union['SqlserverflexInstanceOptionsArgs', 'SqlserverflexInstanceOptionsArgsDict']]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 storage: pulumi.Input[Optional[Union['SqlserverflexInstanceStorageArgs', 'SqlserverflexInstanceStorageArgsDict']]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        SQLServer Flex instance resource schema. Must have a `region` specified in the provider configuration.

        ## Example Usage


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acls: The Access Control List (ACL) for the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] backup_schedule: The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] flavor_id: The flavor ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] name: Instance name.
        :param pulumi.Input[Union['SqlserverflexInstanceNetworkArgs', 'SqlserverflexInstanceNetworkArgsDict']] network: The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the instance is associated.
        :param pulumi.Input[_builtins.str] region: The resource region. If not defined, the provider region is used.
        :param pulumi.Input[_builtins.int] retention_days: The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[Union['SqlserverflexInstanceStorageArgs', 'SqlserverflexInstanceStorageArgsDict']] storage: The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] version: The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SqlserverflexInstanceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        SQLServer Flex instance resource schema. Must have a `region` specified in the provider configuration.

        ## Example Usage


        :param str resource_name: The name of the resource.
        :param SqlserverflexInstanceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SqlserverflexInstanceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backup_schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 flavor: pulumi.Input[Optional[Union['SqlserverflexInstanceFlavorArgs', 'SqlserverflexInstanceFlavorArgsDict']]] = None,
                 flavor_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional[Union['SqlserverflexInstanceNetworkArgs', 'SqlserverflexInstanceNetworkArgsDict']]] = None,
                 options: pulumi.Input[Optional[Union['SqlserverflexInstanceOptionsArgs', 'SqlserverflexInstanceOptionsArgsDict']]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 retention_days: pulumi.Input[Optional[_builtins.int]] = None,
                 storage: pulumi.Input[Optional[Union['SqlserverflexInstanceStorageArgs', 'SqlserverflexInstanceStorageArgsDict']]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SqlserverflexInstanceArgs.__new__(SqlserverflexInstanceArgs)

            __props__.__dict__["acls"] = acls
            __props__.__dict__["backup_schedule"] = backup_schedule
            __props__.__dict__["flavor"] = flavor
            __props__.__dict__["flavor_id"] = flavor_id
            __props__.__dict__["name"] = name
            __props__.__dict__["network"] = network
            __props__.__dict__["options"] = options
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["region"] = region
            __props__.__dict__["retention_days"] = retention_days
            __props__.__dict__["storage"] = storage
            __props__.__dict__["version"] = version
            __props__.__dict__["edition"] = None
            __props__.__dict__["instance_id"] = None
            __props__.__dict__["replicas"] = None
        super(SqlserverflexInstance, __self__).__init__(
            'stackit:index/sqlserverflexInstance:SqlserverflexInstance',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            acls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            backup_schedule: pulumi.Input[Optional[_builtins.str]] = None,
            edition: pulumi.Input[Optional[_builtins.str]] = None,
            flavor: pulumi.Input[Optional[Union['SqlserverflexInstanceFlavorArgs', 'SqlserverflexInstanceFlavorArgsDict']]] = None,
            flavor_id: pulumi.Input[Optional[_builtins.str]] = None,
            instance_id: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            network: pulumi.Input[Optional[Union['SqlserverflexInstanceNetworkArgs', 'SqlserverflexInstanceNetworkArgsDict']]] = None,
            options: pulumi.Input[Optional[Union['SqlserverflexInstanceOptionsArgs', 'SqlserverflexInstanceOptionsArgsDict']]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            replicas: pulumi.Input[Optional[_builtins.int]] = None,
            retention_days: pulumi.Input[Optional[_builtins.int]] = None,
            storage: pulumi.Input[Optional[Union['SqlserverflexInstanceStorageArgs', 'SqlserverflexInstanceStorageArgsDict']]] = None,
            version: pulumi.Input[Optional[_builtins.str]] = None) -> 'SqlserverflexInstance':
        """
        Get an existing SqlserverflexInstance resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acls: The Access Control List (ACL) for the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] backup_schedule: The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] edition: Edition of the MSSQL server instance.
        :param pulumi.Input[_builtins.str] flavor_id: The flavor ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] instance_id: ID of the SQLServer Flex instance.
        :param pulumi.Input[_builtins.str] name: Instance name.
        :param pulumi.Input[Union['SqlserverflexInstanceNetworkArgs', 'SqlserverflexInstanceNetworkArgsDict']] network: The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] project_id: STACKIT project ID to which the instance is associated.
        :param pulumi.Input[_builtins.str] region: The resource region. If not defined, the provider region is used.
        :param pulumi.Input[_builtins.int] retention_days: The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[Union['SqlserverflexInstanceStorageArgs', 'SqlserverflexInstanceStorageArgsDict']] storage: The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        :param pulumi.Input[_builtins.str] version: The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SqlserverflexInstanceState.__new__(_SqlserverflexInstanceState)

        __props__.__dict__["acls"] = acls
        __props__.__dict__["backup_schedule"] = backup_schedule
        __props__.__dict__["edition"] = edition
        __props__.__dict__["flavor"] = flavor
        __props__.__dict__["flavor_id"] = flavor_id
        __props__.__dict__["instance_id"] = instance_id
        __props__.__dict__["name"] = name
        __props__.__dict__["network"] = network
        __props__.__dict__["options"] = options
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["region"] = region
        __props__.__dict__["replicas"] = replicas
        __props__.__dict__["retention_days"] = retention_days
        __props__.__dict__["storage"] = storage
        __props__.__dict__["version"] = version
        return SqlserverflexInstance(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""acl is deprecated and will be removed after January 2027. Use instead `network.acl`.""")
    def acls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The Access Control List (ACL) for the SQLServer Flex instance.
        """
        return pulumi.get(self, "acls")

    @_builtins.property
    @pulumi.getter(name="backupSchedule")
    def backup_schedule(self) -> pulumi.Output[_builtins.str]:
        """
        The backup schedule. Should follow the cron scheduling system format (e.g. "0 0 * * *") Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "backup_schedule")

    @_builtins.property
    @pulumi.getter
    def edition(self) -> pulumi.Output[_builtins.str]:
        """
        Edition of the MSSQL server instance.
        """
        return pulumi.get(self, "edition")

    @_builtins.property
    @pulumi.getter
    def flavor(self) -> pulumi.Output['outputs.SqlserverflexInstanceFlavor']:
        return pulumi.get(self, "flavor")

    @_builtins.property
    @pulumi.getter(name="flavorId")
    def flavor_id(self) -> pulumi.Output[_builtins.str]:
        """
        The flavor ID of the SQLServer Flex instance.
        """
        return pulumi.get(self, "flavor_id")

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the SQLServer Flex instance.
        """
        return pulumi.get(self, "instance_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Instance name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def network(self) -> pulumi.Output['outputs.SqlserverflexInstanceNetwork']:
        """
        The network configuration of the instance. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "network")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""option is deprecated and will be removed after January 2027.""")
    def options(self) -> pulumi.Output['outputs.SqlserverflexInstanceOptions']:
        return pulumi.get(self, "options")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        STACKIT project ID to which the instance is associated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        The resource region. If not defined, the provider region is used.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter(name="retentionDays")
    def retention_days(self) -> pulumi.Output[_builtins.int]:
        """
        The days (30 to 90) for how long the backup files should be stored before cleaned up. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "retention_days")

    @_builtins.property
    @pulumi.getter
    def storage(self) -> pulumi.Output['outputs.SqlserverflexInstanceStorage']:
        """
        The object containing information about the storage size and class. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "storage")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        The sqlserver version used for the instance. Possible values are: `2022`. Will be required in the future. Set a value to prevent breaking changes.
        """
        return pulumi.get(self, "version")

