// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class AlbWafManagedRuleSetGroups
    {
        /// <summary>
        /// A description of what this group covers.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The name for the rule group.
        /// </summary>
        public readonly string? GroupName;
        /// <summary>
        /// Rules of the rule group.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.AlbWafManagedRuleSetGroupsRules>? Rules;

        [OutputConstructor]
        private AlbWafManagedRuleSetGroups(
            string? description,

            string? groupName,

            ImmutableDictionary<string, Outputs.AlbWafManagedRuleSetGroupsRules>? rules)
        {
            Description = description;
            GroupName = groupName;
            Rules = rules;
        }
    }
}
