// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class ApplicationLoadBalancerListenerHttpHostRuleQueryParameter
    {
        /// <summary>
        /// Exact match for the query parameters value.
        /// </summary>
        public readonly string? ExactMatch;
        /// <summary>
        /// Query parameter name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ApplicationLoadBalancerListenerHttpHostRuleQueryParameter(
            string? exactMatch,

            string name)
        {
            ExactMatch = exactMatch;
            Name = name;
        }
    }
}
