// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class GetApplicationLoadBalancerOptionsObservabilityResult
    {
        /// <summary>
        /// Observability logs configuration.
        /// </summary>
        public readonly Outputs.GetApplicationLoadBalancerOptionsObservabilityLogsResult Logs;
        /// <summary>
        /// Observability metrics configuration.
        /// </summary>
        public readonly Outputs.GetApplicationLoadBalancerOptionsObservabilityMetricsResult Metrics;

        [OutputConstructor]
        private GetApplicationLoadBalancerOptionsObservabilityResult(
            Outputs.GetApplicationLoadBalancerOptionsObservabilityLogsResult logs,

            Outputs.GetApplicationLoadBalancerOptionsObservabilityMetricsResult metrics)
        {
            Logs = logs;
            Metrics = metrics;
        }
    }
}
