// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class GetImageV2ChecksumResult
    {
        /// <summary>
        /// Algorithm for the checksum of the image data.
        /// </summary>
        public readonly string Algorithm;
        /// <summary>
        /// Hexdigest of the checksum of the image data.
        /// </summary>
        public readonly string Digest;

        [OutputConstructor]
        private GetImageV2ChecksumResult(
            string algorithm,

            string digest)
        {
            Algorithm = algorithm;
            Digest = digest;
        }
    }
}
