// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class GetLoadbalancerOptionsObservabilityLogsResult
    {
        /// <summary>
        /// Credentials reference for logs.
        /// </summary>
        public readonly string CredentialsRef;
        /// <summary>
        /// Credentials reference for logs.
        /// </summary>
        public readonly string PushUrl;

        [OutputConstructor]
        private GetLoadbalancerOptionsObservabilityLogsResult(
            string credentialsRef,

            string pushUrl)
        {
            CredentialsRef = credentialsRef;
            PushUrl = pushUrl;
        }
    }
}
