// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class GetRoutingTableRoutesRouteResult
    {
        /// <summary>
        /// Date-time when the route was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Destination of the route.
        /// </summary>
        public readonly Outputs.GetRoutingTableRoutesRouteDestinationResult Destination;
        /// <summary>
        /// Labels are key-value string pairs which can be attached to a resource container
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// Next hop destination.
        /// </summary>
        public readonly Outputs.GetRoutingTableRoutesRouteNextHopResult NextHop;
        /// <summary>
        /// Route ID.
        /// </summary>
        public readonly string RouteId;
        /// <summary>
        /// Date-time when the route was updated
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetRoutingTableRoutesRouteResult(
            string createdAt,

            Outputs.GetRoutingTableRoutesRouteDestinationResult destination,

            ImmutableDictionary<string, string> labels,

            Outputs.GetRoutingTableRoutesRouteNextHopResult nextHop,

            string routeId,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Destination = destination;
            Labels = labels;
            NextHop = nextHop;
            RouteId = routeId;
            UpdatedAt = updatedAt;
        }
    }
}
