// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class GetVpnConnectionTunnel1Result
    {
        /// <summary>
        /// BGP configuration for this tunnel.
        /// </summary>
        public readonly Outputs.GetVpnConnectionTunnel1BgpResult Bgp;
        /// <summary>
        /// Tunnel interface peering configuration.
        /// </summary>
        public readonly Outputs.GetVpnConnectionTunnel1PeeringResult Peering;
        /// <summary>
        /// IKE Phase 1 configuration.
        /// </summary>
        public readonly Outputs.GetVpnConnectionTunnel1Phase1Result Phase1;
        /// <summary>
        /// IKE Phase 2 configuration.
        /// </summary>
        public readonly Outputs.GetVpnConnectionTunnel1Phase2Result Phase2;
        /// <summary>
        /// Remote peer IPv4 address for this tunnel.
        /// </summary>
        public readonly string RemoteAddress;

        [OutputConstructor]
        private GetVpnConnectionTunnel1Result(
            Outputs.GetVpnConnectionTunnel1BgpResult bgp,

            Outputs.GetVpnConnectionTunnel1PeeringResult peering,

            Outputs.GetVpnConnectionTunnel1Phase1Result phase1,

            Outputs.GetVpnConnectionTunnel1Phase2Result phase2,

            string remoteAddress)
        {
            Bgp = bgp;
            Peering = peering;
            Phase1 = phase1;
            Phase2 = phase2;
            RemoteAddress = remoteAddress;
        }
    }
}
