// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class ObservabilityScrapeconfigSaml2
    {
        /// <summary>
        /// Specifies if URL parameters are enabled. Defaults to `true`
        /// </summary>
        public readonly bool? EnableUrlParameters;

        [OutputConstructor]
        private ObservabilityScrapeconfigSaml2(bool? enableUrlParameters)
        {
            EnableUrlParameters = enableUrlParameters;
        }
    }
}
