// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Outputs
{

    [OutputType]
    public sealed class SkeClusterExtensionsAcl
    {
        /// <summary>
        /// Specify a list of CIDRs to whitelist.
        /// </summary>
        public readonly ImmutableArray<string> AllowedCidrs;
        /// <summary>
        /// Is ACL enabled?
        /// </summary>
        public readonly bool Enabled;

        [OutputConstructor]
        private SkeClusterExtensionsAcl(
            ImmutableArray<string> allowedCidrs,

            bool enabled)
        {
            AllowedCidrs = allowedCidrs;
            Enabled = enabled;
        }
    }
}
