// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package stackit

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/stackitcloud/pulumi-stackit/sdk/go/stackit/internal"
)

// Custom Role resource schema.
//
// ## Example Usage
type AuthorizationOrganizationCustomRole struct {
	pulumi.CustomResourceState

	// A human readable description of the role.
	Description pulumi.StringOutput `pulumi:"description"`
	// Name of the role
	Name pulumi.StringOutput `pulumi:"name"`
	// Permissions for the role
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
	// Resource to add the custom role to.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// The ID of the role.
	RoleId pulumi.StringOutput `pulumi:"roleId"`
}

// NewAuthorizationOrganizationCustomRole registers a new resource with the given unique name, arguments, and options.
func NewAuthorizationOrganizationCustomRole(ctx *pulumi.Context,
	name string, args *AuthorizationOrganizationCustomRoleArgs, opts ...pulumi.ResourceOption) (*AuthorizationOrganizationCustomRole, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	if args.ResourceId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AuthorizationOrganizationCustomRole
	err := ctx.RegisterResource("stackit:index/authorizationOrganizationCustomRole:AuthorizationOrganizationCustomRole", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthorizationOrganizationCustomRole gets an existing AuthorizationOrganizationCustomRole resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthorizationOrganizationCustomRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthorizationOrganizationCustomRoleState, opts ...pulumi.ResourceOption) (*AuthorizationOrganizationCustomRole, error) {
	var resource AuthorizationOrganizationCustomRole
	err := ctx.ReadResource("stackit:index/authorizationOrganizationCustomRole:AuthorizationOrganizationCustomRole", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthorizationOrganizationCustomRole resources.
type authorizationOrganizationCustomRoleState struct {
	// A human readable description of the role.
	Description *string `pulumi:"description"`
	// Name of the role
	Name *string `pulumi:"name"`
	// Permissions for the role
	Permissions []string `pulumi:"permissions"`
	// Resource to add the custom role to.
	ResourceId *string `pulumi:"resourceId"`
	// The ID of the role.
	RoleId *string `pulumi:"roleId"`
}

type AuthorizationOrganizationCustomRoleState struct {
	// A human readable description of the role.
	Description pulumi.StringPtrInput
	// Name of the role
	Name pulumi.StringPtrInput
	// Permissions for the role
	Permissions pulumi.StringArrayInput
	// Resource to add the custom role to.
	ResourceId pulumi.StringPtrInput
	// The ID of the role.
	RoleId pulumi.StringPtrInput
}

func (AuthorizationOrganizationCustomRoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*authorizationOrganizationCustomRoleState)(nil)).Elem()
}

type authorizationOrganizationCustomRoleArgs struct {
	// A human readable description of the role.
	Description string `pulumi:"description"`
	// Name of the role
	Name *string `pulumi:"name"`
	// Permissions for the role
	Permissions []string `pulumi:"permissions"`
	// Resource to add the custom role to.
	ResourceId string `pulumi:"resourceId"`
}

// The set of arguments for constructing a AuthorizationOrganizationCustomRole resource.
type AuthorizationOrganizationCustomRoleArgs struct {
	// A human readable description of the role.
	Description pulumi.StringInput
	// Name of the role
	Name pulumi.StringPtrInput
	// Permissions for the role
	Permissions pulumi.StringArrayInput
	// Resource to add the custom role to.
	ResourceId pulumi.StringInput
}

func (AuthorizationOrganizationCustomRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authorizationOrganizationCustomRoleArgs)(nil)).Elem()
}

type AuthorizationOrganizationCustomRoleInput interface {
	pulumi.Input

	ToAuthorizationOrganizationCustomRoleOutput() AuthorizationOrganizationCustomRoleOutput
	ToAuthorizationOrganizationCustomRoleOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleOutput
}

func (*AuthorizationOrganizationCustomRole) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (i *AuthorizationOrganizationCustomRole) ToAuthorizationOrganizationCustomRoleOutput() AuthorizationOrganizationCustomRoleOutput {
	return i.ToAuthorizationOrganizationCustomRoleOutputWithContext(context.Background())
}

func (i *AuthorizationOrganizationCustomRole) ToAuthorizationOrganizationCustomRoleOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationOrganizationCustomRoleOutput)
}

// AuthorizationOrganizationCustomRoleArrayInput is an input type that accepts AuthorizationOrganizationCustomRoleArray and AuthorizationOrganizationCustomRoleArrayOutput values.
// You can construct a concrete instance of `AuthorizationOrganizationCustomRoleArrayInput` via:
//
//	AuthorizationOrganizationCustomRoleArray{ AuthorizationOrganizationCustomRoleArgs{...} }
type AuthorizationOrganizationCustomRoleArrayInput interface {
	pulumi.Input

	ToAuthorizationOrganizationCustomRoleArrayOutput() AuthorizationOrganizationCustomRoleArrayOutput
	ToAuthorizationOrganizationCustomRoleArrayOutputWithContext(context.Context) AuthorizationOrganizationCustomRoleArrayOutput
}

type AuthorizationOrganizationCustomRoleArray []AuthorizationOrganizationCustomRoleInput

func (AuthorizationOrganizationCustomRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (i AuthorizationOrganizationCustomRoleArray) ToAuthorizationOrganizationCustomRoleArrayOutput() AuthorizationOrganizationCustomRoleArrayOutput {
	return i.ToAuthorizationOrganizationCustomRoleArrayOutputWithContext(context.Background())
}

func (i AuthorizationOrganizationCustomRoleArray) ToAuthorizationOrganizationCustomRoleArrayOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationOrganizationCustomRoleArrayOutput)
}

// AuthorizationOrganizationCustomRoleMapInput is an input type that accepts AuthorizationOrganizationCustomRoleMap and AuthorizationOrganizationCustomRoleMapOutput values.
// You can construct a concrete instance of `AuthorizationOrganizationCustomRoleMapInput` via:
//
//	AuthorizationOrganizationCustomRoleMap{ "key": AuthorizationOrganizationCustomRoleArgs{...} }
type AuthorizationOrganizationCustomRoleMapInput interface {
	pulumi.Input

	ToAuthorizationOrganizationCustomRoleMapOutput() AuthorizationOrganizationCustomRoleMapOutput
	ToAuthorizationOrganizationCustomRoleMapOutputWithContext(context.Context) AuthorizationOrganizationCustomRoleMapOutput
}

type AuthorizationOrganizationCustomRoleMap map[string]AuthorizationOrganizationCustomRoleInput

func (AuthorizationOrganizationCustomRoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (i AuthorizationOrganizationCustomRoleMap) ToAuthorizationOrganizationCustomRoleMapOutput() AuthorizationOrganizationCustomRoleMapOutput {
	return i.ToAuthorizationOrganizationCustomRoleMapOutputWithContext(context.Background())
}

func (i AuthorizationOrganizationCustomRoleMap) ToAuthorizationOrganizationCustomRoleMapOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationOrganizationCustomRoleMapOutput)
}

type AuthorizationOrganizationCustomRoleOutput struct{ *pulumi.OutputState }

func (AuthorizationOrganizationCustomRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (o AuthorizationOrganizationCustomRoleOutput) ToAuthorizationOrganizationCustomRoleOutput() AuthorizationOrganizationCustomRoleOutput {
	return o
}

func (o AuthorizationOrganizationCustomRoleOutput) ToAuthorizationOrganizationCustomRoleOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleOutput {
	return o
}

// A human readable description of the role.
func (o AuthorizationOrganizationCustomRoleOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthorizationOrganizationCustomRole) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Name of the role
func (o AuthorizationOrganizationCustomRoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthorizationOrganizationCustomRole) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Permissions for the role
func (o AuthorizationOrganizationCustomRoleOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthorizationOrganizationCustomRole) pulumi.StringArrayOutput { return v.Permissions }).(pulumi.StringArrayOutput)
}

// Resource to add the custom role to.
func (o AuthorizationOrganizationCustomRoleOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthorizationOrganizationCustomRole) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// The ID of the role.
func (o AuthorizationOrganizationCustomRoleOutput) RoleId() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthorizationOrganizationCustomRole) pulumi.StringOutput { return v.RoleId }).(pulumi.StringOutput)
}

type AuthorizationOrganizationCustomRoleArrayOutput struct{ *pulumi.OutputState }

func (AuthorizationOrganizationCustomRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (o AuthorizationOrganizationCustomRoleArrayOutput) ToAuthorizationOrganizationCustomRoleArrayOutput() AuthorizationOrganizationCustomRoleArrayOutput {
	return o
}

func (o AuthorizationOrganizationCustomRoleArrayOutput) ToAuthorizationOrganizationCustomRoleArrayOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleArrayOutput {
	return o
}

func (o AuthorizationOrganizationCustomRoleArrayOutput) Index(i pulumi.IntInput) AuthorizationOrganizationCustomRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AuthorizationOrganizationCustomRole {
		return vs[0].([]*AuthorizationOrganizationCustomRole)[vs[1].(int)]
	}).(AuthorizationOrganizationCustomRoleOutput)
}

type AuthorizationOrganizationCustomRoleMapOutput struct{ *pulumi.OutputState }

func (AuthorizationOrganizationCustomRoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthorizationOrganizationCustomRole)(nil)).Elem()
}

func (o AuthorizationOrganizationCustomRoleMapOutput) ToAuthorizationOrganizationCustomRoleMapOutput() AuthorizationOrganizationCustomRoleMapOutput {
	return o
}

func (o AuthorizationOrganizationCustomRoleMapOutput) ToAuthorizationOrganizationCustomRoleMapOutputWithContext(ctx context.Context) AuthorizationOrganizationCustomRoleMapOutput {
	return o
}

func (o AuthorizationOrganizationCustomRoleMapOutput) MapIndex(k pulumi.StringInput) AuthorizationOrganizationCustomRoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AuthorizationOrganizationCustomRole {
		return vs[0].(map[string]*AuthorizationOrganizationCustomRole)[vs[1].(string)]
	}).(AuthorizationOrganizationCustomRoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationOrganizationCustomRoleInput)(nil)).Elem(), &AuthorizationOrganizationCustomRole{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationOrganizationCustomRoleArrayInput)(nil)).Elem(), AuthorizationOrganizationCustomRoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationOrganizationCustomRoleMapInput)(nil)).Elem(), AuthorizationOrganizationCustomRoleMap{})
	pulumi.RegisterOutputType(AuthorizationOrganizationCustomRoleOutput{})
	pulumi.RegisterOutputType(AuthorizationOrganizationCustomRoleArrayOutput{})
	pulumi.RegisterOutputType(AuthorizationOrganizationCustomRoleMapOutput{})
}
