// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package stackit

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/stackitcloud/pulumi-stackit/sdk/go/stackit/internal"
)

// ALB WAF Managed Rule Set DataSource schema. Uses the `defaultRegion` specified in the provider configuration as a fallback in case no `region` is defined on datasource level.
//
// > This datasource is in beta and may be subject to breaking changes in the future. Use with caution. See our guide for how to opt-in to use beta resources.
//
// ## Example Usage
func LookupAlbWafManagedRuleSet(ctx *pulumi.Context, args *LookupAlbWafManagedRuleSetArgs, opts ...pulumi.InvokeOption) (*LookupAlbWafManagedRuleSetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAlbWafManagedRuleSetResult
	err := ctx.Invoke("stackit:index/getAlbWafManagedRuleSet:getAlbWafManagedRuleSet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAlbWafManagedRuleSet.
type LookupAlbWafManagedRuleSetArgs struct {
	// Managed Rule Set configuration name.
	Name string `pulumi:"name"`
	// STACKIT project ID associated with the ALB WAF Managed Rule Set.
	ProjectId string `pulumi:"projectId"`
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region *string `pulumi:"region"`
}

// A collection of values returned by getAlbWafManagedRuleSet.
type LookupAlbWafManagedRuleSetResult struct {
	// Inventory of all available Managed Rule Set groups and their current configuration.
	Groups map[string]GetAlbWafManagedRuleSetGroups `pulumi:"groups"`
	// Terraform's internal resource identifier. Structured as "`projectId`,`region`,`name`".
	Id string `pulumi:"id"`
	// Managed Rule Set configuration name.
	Name string `pulumi:"name"`
	// STACKIT project ID associated with the ALB WAF Managed Rule Set.
	ProjectId string `pulumi:"projectId"`
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region string `pulumi:"region"`
	// Type of the Managed Rule Set.
	Type string `pulumi:"type"`
	// Managed Rule Set version.
	Version string `pulumi:"version"`
}

func LookupAlbWafManagedRuleSetOutput(ctx *pulumi.Context, args LookupAlbWafManagedRuleSetOutputArgs, opts ...pulumi.InvokeOption) LookupAlbWafManagedRuleSetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAlbWafManagedRuleSetResultOutput, error) {
			args := v.(LookupAlbWafManagedRuleSetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("stackit:index/getAlbWafManagedRuleSet:getAlbWafManagedRuleSet", args, LookupAlbWafManagedRuleSetResultOutput{}, options).(LookupAlbWafManagedRuleSetResultOutput), nil
		}).(LookupAlbWafManagedRuleSetResultOutput)
}

// A collection of arguments for invoking getAlbWafManagedRuleSet.
type LookupAlbWafManagedRuleSetOutputArgs struct {
	// Managed Rule Set configuration name.
	Name pulumi.StringInput `pulumi:"name"`
	// STACKIT project ID associated with the ALB WAF Managed Rule Set.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region pulumi.StringPtrInput `pulumi:"region"`
}

func (LookupAlbWafManagedRuleSetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlbWafManagedRuleSetArgs)(nil)).Elem()
}

// A collection of values returned by getAlbWafManagedRuleSet.
type LookupAlbWafManagedRuleSetResultOutput struct{ *pulumi.OutputState }

func (LookupAlbWafManagedRuleSetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlbWafManagedRuleSetResult)(nil)).Elem()
}

func (o LookupAlbWafManagedRuleSetResultOutput) ToLookupAlbWafManagedRuleSetResultOutput() LookupAlbWafManagedRuleSetResultOutput {
	return o
}

func (o LookupAlbWafManagedRuleSetResultOutput) ToLookupAlbWafManagedRuleSetResultOutputWithContext(ctx context.Context) LookupAlbWafManagedRuleSetResultOutput {
	return o
}

// Inventory of all available Managed Rule Set groups and their current configuration.
func (o LookupAlbWafManagedRuleSetResultOutput) Groups() GetAlbWafManagedRuleSetGroupsMapOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) map[string]GetAlbWafManagedRuleSetGroups { return v.Groups }).(GetAlbWafManagedRuleSetGroupsMapOutput)
}

// Terraform's internal resource identifier. Structured as "`projectId`,`region`,`name`".
func (o LookupAlbWafManagedRuleSetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.Id }).(pulumi.StringOutput)
}

// Managed Rule Set configuration name.
func (o LookupAlbWafManagedRuleSetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.Name }).(pulumi.StringOutput)
}

// STACKIT project ID associated with the ALB WAF Managed Rule Set.
func (o LookupAlbWafManagedRuleSetResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// STACKIT region name the resource is located in. If not defined, the provider region is used.
func (o LookupAlbWafManagedRuleSetResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.Region }).(pulumi.StringOutput)
}

// Type of the Managed Rule Set.
func (o LookupAlbWafManagedRuleSetResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.Type }).(pulumi.StringOutput)
}

// Managed Rule Set version.
func (o LookupAlbWafManagedRuleSetResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbWafManagedRuleSetResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAlbWafManagedRuleSetResultOutput{})
}
