// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package stackit

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/stackitcloud/pulumi-stackit/sdk/go/stackit/internal"
)

// Manages a STACKIT Dremio instances user.
//
// > This datasource is part of the experimental feature dremio and is likely going to undergo significant changes or be removed in the future. Use it at your own discretion.
//
// ## Example Usage
func LookupDremioUser(ctx *pulumi.Context, args *LookupDremioUserArgs, opts ...pulumi.InvokeOption) (*LookupDremioUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDremioUserResult
	err := ctx.Invoke("stackit:index/getDremioUser:getDremioUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDremioUser.
type LookupDremioUserArgs struct {
	// The description of the user.
	Description *string `pulumi:"description"`
	// The Dremio instance ID.
	InstanceId string `pulumi:"instanceId"`
	// STACKIT Project ID to which the resource is associated.
	ProjectId string `pulumi:"projectId"`
	// The STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region *string `pulumi:"region"`
	// The Dremio user ID.
	UserId string `pulumi:"userId"`
}

// A collection of values returned by getDremioUser.
type LookupDremioUserResult struct {
	// The description of the user.
	Description string `pulumi:"description"`
	// The email address of the user.
	Email string `pulumi:"email"`
	// The first name of the user.
	FirstName string `pulumi:"firstName"`
	// Terraform's internal resource identifier. It is structured as "`projectId`,`region`,`instanceId`,`userId`".
	Id string `pulumi:"id"`
	// The Dremio instance ID.
	InstanceId string `pulumi:"instanceId"`
	// The last name of the user.
	LastName string `pulumi:"lastName"`
	// The username of the user.
	Name string `pulumi:"name"`
	// STACKIT Project ID to which the resource is associated.
	ProjectId string `pulumi:"projectId"`
	// The STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region *string `pulumi:"region"`
	// The Dremio user ID.
	UserId string `pulumi:"userId"`
}

func LookupDremioUserOutput(ctx *pulumi.Context, args LookupDremioUserOutputArgs, opts ...pulumi.InvokeOption) LookupDremioUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupDremioUserResultOutput, error) {
			args := v.(LookupDremioUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("stackit:index/getDremioUser:getDremioUser", args, LookupDremioUserResultOutput{}, options).(LookupDremioUserResultOutput), nil
		}).(LookupDremioUserResultOutput)
}

// A collection of arguments for invoking getDremioUser.
type LookupDremioUserOutputArgs struct {
	// The description of the user.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The Dremio instance ID.
	InstanceId pulumi.StringInput `pulumi:"instanceId"`
	// STACKIT Project ID to which the resource is associated.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
	// The STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region pulumi.StringPtrInput `pulumi:"region"`
	// The Dremio user ID.
	UserId pulumi.StringInput `pulumi:"userId"`
}

func (LookupDremioUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDremioUserArgs)(nil)).Elem()
}

// A collection of values returned by getDremioUser.
type LookupDremioUserResultOutput struct{ *pulumi.OutputState }

func (LookupDremioUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDremioUserResult)(nil)).Elem()
}

func (o LookupDremioUserResultOutput) ToLookupDremioUserResultOutput() LookupDremioUserResultOutput {
	return o
}

func (o LookupDremioUserResultOutput) ToLookupDremioUserResultOutputWithContext(ctx context.Context) LookupDremioUserResultOutput {
	return o
}

// The description of the user.
func (o LookupDremioUserResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.Description }).(pulumi.StringOutput)
}

// The email address of the user.
func (o LookupDremioUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// The first name of the user.
func (o LookupDremioUserResultOutput) FirstName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.FirstName }).(pulumi.StringOutput)
}

// Terraform's internal resource identifier. It is structured as "`projectId`,`region`,`instanceId`,`userId`".
func (o LookupDremioUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// The Dremio instance ID.
func (o LookupDremioUserResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

// The last name of the user.
func (o LookupDremioUserResultOutput) LastName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.LastName }).(pulumi.StringOutput)
}

// The username of the user.
func (o LookupDremioUserResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.Name }).(pulumi.StringOutput)
}

// STACKIT Project ID to which the resource is associated.
func (o LookupDremioUserResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// The STACKIT region name the resource is located in. If not defined, the provider region is used.
func (o LookupDremioUserResultOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupDremioUserResult) *string { return v.Region }).(pulumi.StringPtrOutput)
}

// The Dremio user ID.
func (o LookupDremioUserResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDremioUserResult) string { return v.UserId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDremioUserResultOutput{})
}
