// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package stackit

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/stackitcloud/pulumi-stackit/sdk/go/stackit/internal"
)

// Network area region resource schema.
//
// ## Example Usage
type NetworkAreaRegion struct {
	pulumi.CustomResourceState

	// The regional IPv4 config of a network area.
	Ipv4 NetworkAreaRegionIpv4Output `pulumi:"ipv4"`
	// The network area ID.
	NetworkAreaId pulumi.StringOutput `pulumi:"networkAreaId"`
	// STACKIT organization ID to which the network area is associated.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// The resource region. If not defined, the provider region is used.
	Region pulumi.StringOutput `pulumi:"region"`
}

// NewNetworkAreaRegion registers a new resource with the given unique name, arguments, and options.
func NewNetworkAreaRegion(ctx *pulumi.Context,
	name string, args *NetworkAreaRegionArgs, opts ...pulumi.ResourceOption) (*NetworkAreaRegion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Ipv4 == nil {
		return nil, errors.New("invalid value for required argument 'Ipv4'")
	}
	if args.NetworkAreaId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkAreaId'")
	}
	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetworkAreaRegion
	err := ctx.RegisterResource("stackit:index/networkAreaRegion:NetworkAreaRegion", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkAreaRegion gets an existing NetworkAreaRegion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkAreaRegion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkAreaRegionState, opts ...pulumi.ResourceOption) (*NetworkAreaRegion, error) {
	var resource NetworkAreaRegion
	err := ctx.ReadResource("stackit:index/networkAreaRegion:NetworkAreaRegion", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkAreaRegion resources.
type networkAreaRegionState struct {
	// The regional IPv4 config of a network area.
	Ipv4 *NetworkAreaRegionIpv4 `pulumi:"ipv4"`
	// The network area ID.
	NetworkAreaId *string `pulumi:"networkAreaId"`
	// STACKIT organization ID to which the network area is associated.
	OrganizationId *string `pulumi:"organizationId"`
	// The resource region. If not defined, the provider region is used.
	Region *string `pulumi:"region"`
}

type NetworkAreaRegionState struct {
	// The regional IPv4 config of a network area.
	Ipv4 NetworkAreaRegionIpv4PtrInput
	// The network area ID.
	NetworkAreaId pulumi.StringPtrInput
	// STACKIT organization ID to which the network area is associated.
	OrganizationId pulumi.StringPtrInput
	// The resource region. If not defined, the provider region is used.
	Region pulumi.StringPtrInput
}

func (NetworkAreaRegionState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAreaRegionState)(nil)).Elem()
}

type networkAreaRegionArgs struct {
	// The regional IPv4 config of a network area.
	Ipv4 NetworkAreaRegionIpv4 `pulumi:"ipv4"`
	// The network area ID.
	NetworkAreaId string `pulumi:"networkAreaId"`
	// STACKIT organization ID to which the network area is associated.
	OrganizationId string `pulumi:"organizationId"`
	// The resource region. If not defined, the provider region is used.
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a NetworkAreaRegion resource.
type NetworkAreaRegionArgs struct {
	// The regional IPv4 config of a network area.
	Ipv4 NetworkAreaRegionIpv4Input
	// The network area ID.
	NetworkAreaId pulumi.StringInput
	// STACKIT organization ID to which the network area is associated.
	OrganizationId pulumi.StringInput
	// The resource region. If not defined, the provider region is used.
	Region pulumi.StringPtrInput
}

func (NetworkAreaRegionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAreaRegionArgs)(nil)).Elem()
}

type NetworkAreaRegionInput interface {
	pulumi.Input

	ToNetworkAreaRegionOutput() NetworkAreaRegionOutput
	ToNetworkAreaRegionOutputWithContext(ctx context.Context) NetworkAreaRegionOutput
}

func (*NetworkAreaRegion) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAreaRegion)(nil)).Elem()
}

func (i *NetworkAreaRegion) ToNetworkAreaRegionOutput() NetworkAreaRegionOutput {
	return i.ToNetworkAreaRegionOutputWithContext(context.Background())
}

func (i *NetworkAreaRegion) ToNetworkAreaRegionOutputWithContext(ctx context.Context) NetworkAreaRegionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkAreaRegionOutput)
}

// NetworkAreaRegionArrayInput is an input type that accepts NetworkAreaRegionArray and NetworkAreaRegionArrayOutput values.
// You can construct a concrete instance of `NetworkAreaRegionArrayInput` via:
//
//	NetworkAreaRegionArray{ NetworkAreaRegionArgs{...} }
type NetworkAreaRegionArrayInput interface {
	pulumi.Input

	ToNetworkAreaRegionArrayOutput() NetworkAreaRegionArrayOutput
	ToNetworkAreaRegionArrayOutputWithContext(context.Context) NetworkAreaRegionArrayOutput
}

type NetworkAreaRegionArray []NetworkAreaRegionInput

func (NetworkAreaRegionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkAreaRegion)(nil)).Elem()
}

func (i NetworkAreaRegionArray) ToNetworkAreaRegionArrayOutput() NetworkAreaRegionArrayOutput {
	return i.ToNetworkAreaRegionArrayOutputWithContext(context.Background())
}

func (i NetworkAreaRegionArray) ToNetworkAreaRegionArrayOutputWithContext(ctx context.Context) NetworkAreaRegionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkAreaRegionArrayOutput)
}

// NetworkAreaRegionMapInput is an input type that accepts NetworkAreaRegionMap and NetworkAreaRegionMapOutput values.
// You can construct a concrete instance of `NetworkAreaRegionMapInput` via:
//
//	NetworkAreaRegionMap{ "key": NetworkAreaRegionArgs{...} }
type NetworkAreaRegionMapInput interface {
	pulumi.Input

	ToNetworkAreaRegionMapOutput() NetworkAreaRegionMapOutput
	ToNetworkAreaRegionMapOutputWithContext(context.Context) NetworkAreaRegionMapOutput
}

type NetworkAreaRegionMap map[string]NetworkAreaRegionInput

func (NetworkAreaRegionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkAreaRegion)(nil)).Elem()
}

func (i NetworkAreaRegionMap) ToNetworkAreaRegionMapOutput() NetworkAreaRegionMapOutput {
	return i.ToNetworkAreaRegionMapOutputWithContext(context.Background())
}

func (i NetworkAreaRegionMap) ToNetworkAreaRegionMapOutputWithContext(ctx context.Context) NetworkAreaRegionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkAreaRegionMapOutput)
}

type NetworkAreaRegionOutput struct{ *pulumi.OutputState }

func (NetworkAreaRegionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAreaRegion)(nil)).Elem()
}

func (o NetworkAreaRegionOutput) ToNetworkAreaRegionOutput() NetworkAreaRegionOutput {
	return o
}

func (o NetworkAreaRegionOutput) ToNetworkAreaRegionOutputWithContext(ctx context.Context) NetworkAreaRegionOutput {
	return o
}

// The regional IPv4 config of a network area.
func (o NetworkAreaRegionOutput) Ipv4() NetworkAreaRegionIpv4Output {
	return o.ApplyT(func(v *NetworkAreaRegion) NetworkAreaRegionIpv4Output { return v.Ipv4 }).(NetworkAreaRegionIpv4Output)
}

// The network area ID.
func (o NetworkAreaRegionOutput) NetworkAreaId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAreaRegion) pulumi.StringOutput { return v.NetworkAreaId }).(pulumi.StringOutput)
}

// STACKIT organization ID to which the network area is associated.
func (o NetworkAreaRegionOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAreaRegion) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// The resource region. If not defined, the provider region is used.
func (o NetworkAreaRegionOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAreaRegion) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

type NetworkAreaRegionArrayOutput struct{ *pulumi.OutputState }

func (NetworkAreaRegionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkAreaRegion)(nil)).Elem()
}

func (o NetworkAreaRegionArrayOutput) ToNetworkAreaRegionArrayOutput() NetworkAreaRegionArrayOutput {
	return o
}

func (o NetworkAreaRegionArrayOutput) ToNetworkAreaRegionArrayOutputWithContext(ctx context.Context) NetworkAreaRegionArrayOutput {
	return o
}

func (o NetworkAreaRegionArrayOutput) Index(i pulumi.IntInput) NetworkAreaRegionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NetworkAreaRegion {
		return vs[0].([]*NetworkAreaRegion)[vs[1].(int)]
	}).(NetworkAreaRegionOutput)
}

type NetworkAreaRegionMapOutput struct{ *pulumi.OutputState }

func (NetworkAreaRegionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkAreaRegion)(nil)).Elem()
}

func (o NetworkAreaRegionMapOutput) ToNetworkAreaRegionMapOutput() NetworkAreaRegionMapOutput {
	return o
}

func (o NetworkAreaRegionMapOutput) ToNetworkAreaRegionMapOutputWithContext(ctx context.Context) NetworkAreaRegionMapOutput {
	return o
}

func (o NetworkAreaRegionMapOutput) MapIndex(k pulumi.StringInput) NetworkAreaRegionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NetworkAreaRegion {
		return vs[0].(map[string]*NetworkAreaRegion)[vs[1].(string)]
	}).(NetworkAreaRegionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkAreaRegionInput)(nil)).Elem(), &NetworkAreaRegion{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkAreaRegionArrayInput)(nil)).Elem(), NetworkAreaRegionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkAreaRegionMapInput)(nil)).Elem(), NetworkAreaRegionMap{})
	pulumi.RegisterOutputType(NetworkAreaRegionOutput{})
	pulumi.RegisterOutputType(NetworkAreaRegionArrayOutput{})
	pulumi.RegisterOutputType(NetworkAreaRegionMapOutput{})
}
