// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class AlbWafCustomRuleGroupRuleConditionOperatorGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The operational evaluation type definition macro.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The text or rule regex pattern arguments applied inside the operator execution loop.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public AlbWafCustomRuleGroupRuleConditionOperatorGetArgs()
        {
        }
        public static new AlbWafCustomRuleGroupRuleConditionOperatorGetArgs Empty => new AlbWafCustomRuleGroupRuleConditionOperatorGetArgs();
    }
}
