// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class CdnDistributionConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configured backend for the distribution
        /// </summary>
        [Input("backend", required: true)]
        public Input<Inputs.CdnDistributionConfigBackendGetArgs> Backend { get; set; } = null!;

        [Input("blockedCountries")]
        private InputList<string>? _blockedCountries;

        /// <summary>
        /// The configured countries where distribution of content is blocked
        /// </summary>
        public InputList<string> BlockedCountries
        {
            get => _blockedCountries ?? (_blockedCountries = new InputList<string>());
            set => _blockedCountries = value;
        }

        /// <summary>
        /// Configuration for the Image Optimizer. This is a paid feature that automatically optimizes images to reduce their file size for faster delivery, leading to improved website performance and a better user experience.
        /// </summary>
        [Input("optimizer")]
        public Input<Inputs.CdnDistributionConfigOptimizerGetArgs>? Optimizer { get; set; }

        /// <summary>
        /// A wrapper for a list of redirect rules that allows for redirect settings on a distribution
        /// </summary>
        [Input("redirects")]
        public Input<Inputs.CdnDistributionConfigRedirectsGetArgs>? Redirects { get; set; }

        [Input("regions", required: true)]
        private InputList<string>? _regions;

        /// <summary>
        /// The configured regions where content will be hosted
        /// </summary>
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        /// <summary>
        /// Configures the Web Application Firewall (WAF) for the distribution. If this block is undefined or removed from your configuration, the WAF mode will default to DISABLED and the type to FREE. All other WAF properties will retain their last known state in the API; if they were never defined, the API will apply its default settings.
        /// </summary>
        [Input("waf")]
        public Input<Inputs.CdnDistributionConfigWafGetArgs>? Waf { get; set; }

        public CdnDistributionConfigGetArgs()
        {
        }
        public static new CdnDistributionConfigGetArgs Empty => new CdnDistributionConfigGetArgs();
    }
}
