// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class CdnDistributionConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configured backend for the distribution
        /// </summary>
        [Input("backend", required: true)]
        public Input<Inputs.CdnDistributionConfigBackendGetArgs> Backend { get; set; } = null!;

        [Input("blockedCountries")]
        private InputList<string>? _blockedCountries;

        /// <summary>
        /// The configured countries where distribution of content is blocked
        /// </summary>
        public InputList<string> BlockedCountries
        {
            get => _blockedCountries ?? (_blockedCountries = new InputList<string>());
            set => _blockedCountries = value;
        }

        [Input("blockedIps")]
        private InputList<string>? _blockedIps;

        /// <summary>
        /// Restricts access to your content by specifying a list of blocked IPv4 addresses. This feature enhances security and privacy by preventing these addresses from accessing your distribution. Note: once a value is set, removing the attribute from your configuration will retain the last known value in state; to clear it explicitly, set it to an empty list.
        /// </summary>
        public InputList<string> BlockedIps
        {
            get => _blockedIps ?? (_blockedIps = new InputList<string>());
            set => _blockedIps = value;
        }

        /// <summary>
        /// Sets the default cache duration for the distribution. The default cache duration is applied when a 'Cache-Control' header is not presented in the origin's response. We use ISO8601 duration format for cache duration (e.g. P1DT2H30M). Note: once a value is set, removing the attribute from your configuration will retain the last known value in state.
        /// </summary>
        [Input("defaultCacheDuration")]
        public Input<string>? DefaultCacheDuration { get; set; }

        /// <summary>
        /// Enable this allows the 'Host' header to be passed through to the origin.
        /// </summary>
        [Input("forwardHostHeader")]
        public Input<bool>? ForwardHostHeader { get; set; }

        /// <summary>
        /// Sets the monthly limit of bandwidth in bytes that the pullzone is allowed to use. Note: once a value is set, removing the attribute from your configuration will retain the last known value in state.
        /// </summary>
        [Input("monthlyLimitBytes")]
        public Input<int>? MonthlyLimitBytes { get; set; }

        /// <summary>
        /// Configuration for the Image Optimizer. This is a paid feature that automatically optimizes images to reduce their file size for faster delivery, leading to improved website performance and a better user experience.
        /// </summary>
        [Input("optimizer")]
        public Input<Inputs.CdnDistributionConfigOptimizerGetArgs>? Optimizer { get; set; }

        /// <summary>
        /// A wrapper for a list of redirect rules that allows for redirect settings on a distribution
        /// </summary>
        [Input("redirects")]
        public Input<Inputs.CdnDistributionConfigRedirectsGetArgs>? Redirects { get; set; }

        [Input("regions", required: true)]
        private InputList<string>? _regions;

        /// <summary>
        /// The configured regions where content will be hosted
        /// </summary>
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        /// <summary>
        /// Enable this to prevent origin-level cookies from being forwarded to the end user.
        /// </summary>
        [Input("stripResponseCookies")]
        public Input<bool>? StripResponseCookies { get; set; }

        /// <summary>
        /// Configuration for TLS protocol versions. Note: Enabling older TLS versions (1.0, 1.1) is generally discouraged for security reasons.
        /// </summary>
        [Input("tls")]
        public Input<Inputs.CdnDistributionConfigTlsGetArgs>? Tls { get; set; }

        /// <summary>
        /// Configures the Web Application Firewall (WAF) for the distribution. If this block is undefined or removed from your configuration, the WAF mode will default to DISABLED and the type to FREE. All other WAF properties will retain their last known state in the API; if they were never defined, the API will apply its default settings.
        /// </summary>
        [Input("waf")]
        public Input<Inputs.CdnDistributionConfigWafGetArgs>? Waf { get; set; }

        public CdnDistributionConfigGetArgs()
        {
        }
        public static new CdnDistributionConfigGetArgs Empty => new CdnDistributionConfigGetArgs();
    }
}
