// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class GetImageV2FilterInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Filter images by operating system distribution. For example: `Ubuntu`, `ubuntu-arm64`, `Debian`, `Rhel`, etc.
        /// </summary>
        [Input("distro")]
        public Input<string>? Distro { get; set; }

        /// <summary>
        /// Filter images by operating system type, such as `Linux` or `Windows`.
        /// </summary>
        [Input("os")]
        public Input<string>? Os { get; set; }

        /// <summary>
        /// Filter images with Secure Boot support. Set to `True` to match images that support Secure Boot.
        /// </summary>
        [Input("secureBoot")]
        public Input<bool>? SecureBoot { get; set; }

        /// <summary>
        /// Filter images based on UEFI support. Set to `True` to match images that support UEFI.
        /// </summary>
        [Input("uefi")]
        public Input<bool>? Uefi { get; set; }

        /// <summary>
        /// Filter images by OS distribution version, such as `22.04`, `11`, or `9.1`.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public GetImageV2FilterInputArgs()
        {
        }
        public static new GetImageV2FilterInputArgs Empty => new GetImageV2FilterInputArgs();
    }
}
