// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class LoadbalancerTargetPoolActiveHealthCheckGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Healthy threshold of the health checking.
        /// </summary>
        [Input("healthyThreshold")]
        public Input<int>? HealthyThreshold { get; set; }

        /// <summary>
        /// Interval duration of health checking in seconds.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        /// <summary>
        /// Interval duration threshold of the health checking in seconds.
        /// </summary>
        [Input("intervalJitter")]
        public Input<string>? IntervalJitter { get; set; }

        /// <summary>
        /// Active health checking timeout duration in seconds.
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        /// <summary>
        /// Unhealthy threshold of the health checking.
        /// </summary>
        [Input("unhealthyThreshold")]
        public Input<int>? UnhealthyThreshold { get; set; }

        public LoadbalancerTargetPoolActiveHealthCheckGetArgs()
        {
        }
        public static new LoadbalancerTargetPoolActiveHealthCheckGetArgs Empty => new LoadbalancerTargetPoolActiveHealthCheckGetArgs();
    }
}
