// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Inputs
{

    public sealed class ObservabilityInstanceAlertConfigReceiverArgs : global::Pulumi.ResourceArgs
    {
        [Input("emailConfigs")]
        private InputList<Inputs.ObservabilityInstanceAlertConfigReceiverEmailConfigArgs>? _emailConfigs;

        /// <summary>
        /// List of email configurations.
        /// </summary>
        public InputList<Inputs.ObservabilityInstanceAlertConfigReceiverEmailConfigArgs> EmailConfigs
        {
            get => _emailConfigs ?? (_emailConfigs = new InputList<Inputs.ObservabilityInstanceAlertConfigReceiverEmailConfigArgs>());
            set => _emailConfigs = value;
        }

        /// <summary>
        /// Name of the receiver.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("opsgenieConfigs")]
        private InputList<Inputs.ObservabilityInstanceAlertConfigReceiverOpsgenieConfigArgs>? _opsgenieConfigs;

        /// <summary>
        /// List of OpsGenie configurations.
        /// </summary>
        public InputList<Inputs.ObservabilityInstanceAlertConfigReceiverOpsgenieConfigArgs> OpsgenieConfigs
        {
            get => _opsgenieConfigs ?? (_opsgenieConfigs = new InputList<Inputs.ObservabilityInstanceAlertConfigReceiverOpsgenieConfigArgs>());
            set => _opsgenieConfigs = value;
        }

        [Input("webhooksConfigs")]
        private InputList<Inputs.ObservabilityInstanceAlertConfigReceiverWebhooksConfigArgs>? _webhooksConfigs;

        /// <summary>
        /// List of Webhooks configurations.
        /// </summary>
        public InputList<Inputs.ObservabilityInstanceAlertConfigReceiverWebhooksConfigArgs> WebhooksConfigs
        {
            get => _webhooksConfigs ?? (_webhooksConfigs = new InputList<Inputs.ObservabilityInstanceAlertConfigReceiverWebhooksConfigArgs>());
            set => _webhooksConfigs = value;
        }

        public ObservabilityInstanceAlertConfigReceiverArgs()
        {
        }
        public static new ObservabilityInstanceAlertConfigReceiverArgs Empty => new ObservabilityInstanceAlertConfigReceiverArgs();
    }
}
