// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class PostgresflexInstanceConnectionInfoArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The DNS name and port in the instance overview.
        /// </summary>
        [Input("write")]
        public Input<Inputs.PostgresflexInstanceConnectionInfoWriteArgs>? Write { get; set; }

        public PostgresflexInstanceConnectionInfoArgs()
        {
        }
        public static new PostgresflexInstanceConnectionInfoArgs Empty => new PostgresflexInstanceConnectionInfoArgs();
    }
}
