// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class SkeClusterNetworkControlPlaneGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access scope of the control plane. It defines if the Kubernetes control plane is public or only available inside a STACKIT Network Area.Possible values are: `PUBLIC`, `SNA`. The field is immutable!
        /// </summary>
        [Input("accessScope")]
        public Input<string>? AccessScope { get; set; }

        public SkeClusterNetworkControlPlaneGetArgs()
        {
        }
        public static new SkeClusterNetworkControlPlaneGetArgs Empty => new SkeClusterNetworkControlPlaneGetArgs();
    }
}
