// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class TelemetryrouterDestinationConfigFilterGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("attributes", required: true)]
        private InputList<Inputs.TelemetryrouterDestinationConfigFilterAttributeGetArgs>? _attributes;

        /// <summary>
        /// The TelemetryRouter destination's filter attributes
        /// </summary>
        public InputList<Inputs.TelemetryrouterDestinationConfigFilterAttributeGetArgs> Attributes
        {
            get => _attributes ?? (_attributes = new InputList<Inputs.TelemetryrouterDestinationConfigFilterAttributeGetArgs>());
            set => _attributes = value;
        }

        public TelemetryrouterDestinationConfigFilterGetArgs()
        {
        }
        public static new TelemetryrouterDestinationConfigFilterGetArgs Empty => new TelemetryrouterDestinationConfigFilterGetArgs();
    }
}
