// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class TelemetryrouterDestinationConfigS3GetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// S3 access key configuration
        /// </summary>
        [Input("accessKey")]
        public Input<Inputs.TelemetryrouterDestinationConfigS3AccessKeyGetArgs>? AccessKey { get; set; }

        /// <summary>
        /// S3 bucket name
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        /// <summary>
        /// S3 endpoint
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        public TelemetryrouterDestinationConfigS3GetArgs()
        {
        }
        public static new TelemetryrouterDestinationConfigS3GetArgs Empty => new TelemetryrouterDestinationConfigS3GetArgs();
    }
}
