// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackit.Inputs
{

    public sealed class VpcRoutingTableStaticRouteDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CIDR type. Possible values are: `Cidrv4`, `Cidrv6`. Currently cidrv6 is unsupported.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// CIDR value.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public VpcRoutingTableStaticRouteDestinationArgs()
        {
        }
        public static new VpcRoutingTableStaticRouteDestinationArgs Empty => new VpcRoutingTableStaticRouteDestinationArgs();
    }
}
