// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Edge Cloud is in private Beta and not generally available.
 *  You can contact support if you are interested in trying it out.
 *
 * > This resource is in beta and may be subject to breaking changes in the future. Use with caution. See our guide for how to opt-in to use beta resources.
 *
 * ## Example Usage
 */
export class EdgecloudInstance extends pulumi.CustomResource {
    /**
     * Get an existing EdgecloudInstance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgecloudInstanceState, opts?: pulumi.CustomResourceOptions): EdgecloudInstance {
        return new EdgecloudInstance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stackit:index/edgecloudInstance:EdgecloudInstance';

    /**
     * Returns true if the given object is an instance of EdgecloudInstance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgecloudInstance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgecloudInstance.__pulumiType;
    }

    /**
     * The date and time the creation of the instance was triggered.
     */
    declare public /*out*/ readonly created: pulumi.Output<string>;
    /**
     * Description for your STACKIT Edge Cloud instance. Max length is 256 characters
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Display name shown for the Edge Cloud instance. Has to be a valid hostname, with a length between 4 and 8 characters.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Frontend URL for the Edge Cloud instance.
     */
    declare public /*out*/ readonly frontendUrl: pulumi.Output<string>;
    /**
     * \n\n-\n\n
     */
    declare public /*out*/ readonly instanceId: pulumi.Output<string>;
    /**
     * STACKIT Edge Plan ID for the Edge Cloud instance, has to be the UUID of an existing plan.
     */
    declare public readonly planId: pulumi.Output<string>;
    /**
     * STACKIT project ID to which the Edge Cloud instance is associated.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * STACKIT region to use for the instance, providers defaultRegion will be used if unset.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * instance status
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a EdgecloudInstance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgecloudInstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgecloudInstanceArgs | EdgecloudInstanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgecloudInstanceState | undefined;
            resourceInputs["created"] = state?.created;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["frontendUrl"] = state?.frontendUrl;
            resourceInputs["instanceId"] = state?.instanceId;
            resourceInputs["planId"] = state?.planId;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["region"] = state?.region;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as EdgecloudInstanceArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.planId === undefined && !opts.urn) {
                throw new Error("Missing required property 'planId'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["planId"] = args?.planId;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["region"] = args?.region;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["frontendUrl"] = undefined /*out*/;
            resourceInputs["instanceId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgecloudInstance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EdgecloudInstance resources.
 */
export interface EdgecloudInstanceState {
    /**
     * The date and time the creation of the instance was triggered.
     */
    created?: pulumi.Input<string>;
    /**
     * Description for your STACKIT Edge Cloud instance. Max length is 256 characters
     */
    description?: pulumi.Input<string>;
    /**
     * Display name shown for the Edge Cloud instance. Has to be a valid hostname, with a length between 4 and 8 characters.
     */
    displayName?: pulumi.Input<string>;
    /**
     * Frontend URL for the Edge Cloud instance.
     */
    frontendUrl?: pulumi.Input<string>;
    /**
     * \n\n-\n\n
     */
    instanceId?: pulumi.Input<string>;
    /**
     * STACKIT Edge Plan ID for the Edge Cloud instance, has to be the UUID of an existing plan.
     */
    planId?: pulumi.Input<string>;
    /**
     * STACKIT project ID to which the Edge Cloud instance is associated.
     */
    projectId?: pulumi.Input<string>;
    /**
     * STACKIT region to use for the instance, providers defaultRegion will be used if unset.
     */
    region?: pulumi.Input<string>;
    /**
     * instance status
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EdgecloudInstance resource.
 */
export interface EdgecloudInstanceArgs {
    /**
     * Description for your STACKIT Edge Cloud instance. Max length is 256 characters
     */
    description?: pulumi.Input<string>;
    /**
     * Display name shown for the Edge Cloud instance. Has to be a valid hostname, with a length between 4 and 8 characters.
     */
    displayName: pulumi.Input<string>;
    /**
     * STACKIT Edge Plan ID for the Edge Cloud instance, has to be the UUID of an existing plan.
     */
    planId: pulumi.Input<string>;
    /**
     * STACKIT project ID to which the Edge Cloud instance is associated.
     */
    projectId: pulumi.Input<string>;
    /**
     * STACKIT region to use for the instance, providers defaultRegion will be used if unset.
     */
    region?: pulumi.Input<string>;
}
