// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * SFS project lock resource schema. Must have a `region` specified in the provider configuration. Always use only one project lock per project.
 *
 * ## Example Usage
 */
export function getSfsProjectLock(args: GetSfsProjectLockArgs, opts?: pulumi.InvokeOptions): Promise<GetSfsProjectLockResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("stackit:index/getSfsProjectLock:getSfsProjectLock", {
        "projectId": args.projectId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getSfsProjectLock.
 */
export interface GetSfsProjectLockArgs {
    /**
     * STACKIT Project ID to which the project lock is associated.
     */
    projectId: string;
    /**
     * The resource region. If not defined, the provider region is used.
     */
    region?: string;
}

/**
 * A collection of values returned by getSfsProjectLock.
 */
export interface GetSfsProjectLockResult {
    /**
     * Terraform's internal resource identifier. It is structured as "`projectId`,`region`".
     */
    readonly id: string;
    /**
     * ID of the lock.
     */
    readonly lockId: string;
    /**
     * STACKIT Project ID to which the project lock is associated.
     */
    readonly projectId: string;
    /**
     * The resource region. If not defined, the provider region is used.
     */
    readonly region: string;
}
/**
 * SFS project lock resource schema. Must have a `region` specified in the provider configuration. Always use only one project lock per project.
 *
 * ## Example Usage
 */
export function getSfsProjectLockOutput(args: GetSfsProjectLockOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSfsProjectLockResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("stackit:index/getSfsProjectLock:getSfsProjectLock", {
        "projectId": args.projectId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getSfsProjectLock.
 */
export interface GetSfsProjectLockOutputArgs {
    /**
     * STACKIT Project ID to which the project lock is associated.
     */
    projectId: pulumi.Input<string>;
    /**
     * The resource region. If not defined, the provider region is used.
     */
    region?: pulumi.Input<string>;
}
