// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Network area resource schema.
 *
 * This resource is for SNA, not VPC, networks.
 *
 * ## Example Usage
 *
 * ## Migration of IaaS resources from versions <= v0.78.1
 *
 * The release of the STACKIT IaaS API v2 provides a lot of new features, but also includes some breaking changes
 * (when coming from v1 of the STACKIT IaaS API) which must be somehow represented on Terraform side. The
 * `stackit.NetworkArea` resource deprecated some fields. See the example below how to migrate your resources.
 *
 * ### Migration: Network area resource (stackit_network_area)
 *
 * **Configuration for <= v0.78.1**
 *
 * The previous configuration has some deprecated fields.
 *
 * **Configuration for > v0.78.1**
 *
 * To migrate from a previous state, you need to modify your configuration like this:
 *
 * After modifying the configuration, run `$ pulumi preview` to check what terraform will do.
 * The changes should trigger an update in-place for the existing "stackit.NetworkArea" where the deprecated fields will be removed and the resource "stackit.NetworkAreaRegion" should be imported.
 * It shouldn't trigger any recreation. If terraform wants to recreate any of the resources, verify that you are using the provider version > v0.78.1 and have everything defined correctly.
 *
 * When everything looks good, run `$ pulumi up` to apply these changes.
 * When the run is completed, you can remove the import-block. Run `$ pulumi preview` to verify that the infrastructure matches the configuration.
 */
export class NetworkArea extends pulumi.CustomResource {
    /**
     * Get an existing NetworkArea resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkAreaState, opts?: pulumi.CustomResourceOptions): NetworkArea {
        return new NetworkArea(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stackit:index/networkArea:NetworkArea';

    /**
     * Returns true if the given object is an instance of NetworkArea.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkArea {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkArea.__pulumiType;
    }

    /**
     * Labels are key-value string pairs which can be attached to a resource container
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The name of the network area.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The network area ID.
     */
    declare public /*out*/ readonly networkAreaId: pulumi.Output<string>;
    /**
     * STACKIT organization ID to which the network area is associated.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * The amount of projects currently referencing this area.
     */
    declare public /*out*/ readonly projectCount: pulumi.Output<number>;

    /**
     * Create a NetworkArea resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkAreaArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkAreaArgs | NetworkAreaState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkAreaState | undefined;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkAreaId"] = state?.networkAreaId;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["projectCount"] = state?.projectCount;
        } else {
            const args = argsOrState as NetworkAreaArgs | undefined;
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["networkAreaId"] = undefined /*out*/;
            resourceInputs["projectCount"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkArea.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NetworkArea resources.
 */
export interface NetworkAreaState {
    /**
     * Labels are key-value string pairs which can be attached to a resource container
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The name of the network area.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The network area ID.
     */
    networkAreaId?: pulumi.Input<string | undefined>;
    /**
     * STACKIT organization ID to which the network area is associated.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The amount of projects currently referencing this area.
     */
    projectCount?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a NetworkArea resource.
 */
export interface NetworkAreaArgs {
    /**
     * Labels are key-value string pairs which can be attached to a resource container
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The name of the network area.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * STACKIT organization ID to which the network area is associated.
     */
    organizationId: pulumi.Input<string>;
}
