// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Secrets Manager instance resource schema. Must have a `region` specified in the provider configuration.
 *
 * ## Example Usage
 */
export class SecretsmanagerInstance extends pulumi.CustomResource {
    /**
     * Get an existing SecretsmanagerInstance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsmanagerInstanceState, opts?: pulumi.CustomResourceOptions): SecretsmanagerInstance {
        return new SecretsmanagerInstance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stackit:index/secretsmanagerInstance:SecretsmanagerInstance';

    /**
     * Returns true if the given object is an instance of SecretsmanagerInstance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsmanagerInstance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsmanagerInstance.__pulumiType;
    }

    /**
     * The access control list for this instance. Each entry is an IP or IP range that is permitted to access, in CIDR notation
     */
    declare public readonly acls: pulumi.Output<string[] | undefined>;
    /**
     * ID of the Secrets Manager instance.
     */
    declare public /*out*/ readonly instanceId: pulumi.Output<string>;
    /**
     * Instance name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * STACKIT project ID to which the instance is associated.
     */
    declare public readonly projectId: pulumi.Output<string>;

    /**
     * Create a SecretsmanagerInstance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsmanagerInstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsmanagerInstanceArgs | SecretsmanagerInstanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsmanagerInstanceState | undefined;
            resourceInputs["acls"] = state?.acls;
            resourceInputs["instanceId"] = state?.instanceId;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
        } else {
            const args = argsOrState as SecretsmanagerInstanceArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["acls"] = args?.acls;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["instanceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsmanagerInstance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsmanagerInstance resources.
 */
export interface SecretsmanagerInstanceState {
    /**
     * The access control list for this instance. Each entry is an IP or IP range that is permitted to access, in CIDR notation
     */
    acls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * ID of the Secrets Manager instance.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * Instance name.
     */
    name?: pulumi.Input<string>;
    /**
     * STACKIT project ID to which the instance is associated.
     */
    projectId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecretsmanagerInstance resource.
 */
export interface SecretsmanagerInstanceArgs {
    /**
     * The access control list for this instance. Each entry is an IP or IP range that is permitted to access, in CIDR notation
     */
    acls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Instance name.
     */
    name?: pulumi.Input<string>;
    /**
     * STACKIT project ID to which the instance is associated.
     */
    projectId: pulumi.Input<string>;
}
